<a href="https://colab.research.google.com/github/Osuni-99/Adaptive-AI-DLP-Research/blob/main/notebooks/01_SME_Dataset_Generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install faker python-docx reportlab openpyxl pillow pandas

Collecting faker
  Downloading faker-40.28.1-py3-none-any.whl.metadata (16 kB)
Collecting python-docx
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Collecting reportlab
  Downloading reportlab-5.0.0-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (11.3.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (6.1.1)
Requirement already satisfied: typing_extensions>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (4.15.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.7)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading faker-40.28.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 28.2 MB/s eta 0:00:00
Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 18.4 MB/s eta 0:00:00
Downloading reportlab-5.0.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 57.1 MB/s eta 0:00:00
Installing collected packages: reportlab, python-docx, faker
Successfully installed faker-40.28.1 python-docx-1.2.0 reportlab-5.0.0

In [ ]:
import os
import random
import pandas as pd

from faker import Faker

fake = Faker()

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [ ]:
folders = [

"dataset/Public",

"dataset/Internal",

"dataset/Confidential",

"dataset/Strictly Confidential"

]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Folders Created Successfully")

Folders Created Successfully

In [ ]:
def generate_employee():

    employee = {

        "EmployeeID": fake.random_int(1000,9999),

        "Name": fake.name(),

        "Department": random.choice([
            "HR",
            "Finance",
            "IT",
            "Marketing",
            "Legal"
        ]),

        "Salary": random.randint(50000,300000),

        "NIC": fake.random_number(digits=12),

        "Email": fake.email()

    }

    return employee

In [ ]:
employee = generate_employee()

employee

{'EmployeeID': 1813,
 'Name': 'James Bolton',
 'Department': 'IT',
 'Salary': 236496,
 'NIC': 496708179436,
 'Email': 'gabriela05@example.org'}

In [ ]:
employees = []

for i in range(100):

    employees.append(generate_employee())

df = pd.DataFrame(employees)

df.head()

,EmployeeID,Name,Department,Salary,NIC,Email
0,8221,Heather Mcclure,Finance,141698,657724461340,ydavis@example.com
1,8358,Melissa Shields,Marketing,54683,962825160504,taylorzachary@example.net
2,6166,Benjamin Baker,Finance,82260,847650165343,jakeweiss@example.net
3,7052,Jeffrey Rios,Finance,245379,204681437648,thomasfischer@example.com
4,4636,Anthony Kelly,Marketing,107759,447305084431,lorraine66@example.net

In [ ]:
import os

folders = [
    "dataset/Public",
    "dataset/Internal",
    "dataset/Confidential",
    "dataset/Restricted"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Folders Created Successfully")

Folders Created Successfully

In [ ]:
import os

print(os.listdir("dataset"))

['Strictly Confidential', 'Restricted', 'Confidential', 'Internal', 'Public']

In [ ]:
import os

os.makedirs("dataset/confidential", exist_ok=True)

print("Folder Ready")

Folder Ready

In [ ]:
df.to_csv("dataset/confidential/employees.csv", index=False)

print("CSV Saved Successfully")

CSV Saved Successfully

In [ ]:
import os

os.makedirs("dataset/confidential", exist_ok=True)

print("Folder Ready")

Folder Ready

In [ ]:
df.to_csv("dataset/confidential/employees.csv", index=False)

print("CSV Saved Successfully")

CSV Saved Successfully

In [ ]:
df

,EmployeeID,Name,Department,Salary,NIC,Email
0,8221,Heather Mcclure,Finance,141698,657724461340,ydavis@example.com
1,8358,Melissa Shields,Marketing,54683,962825160504,taylorzachary@example.net
2,6166,Benjamin Baker,Finance,82260,847650165343,jakeweiss@example.net
3,7052,Jeffrey Rios,Finance,245379,204681437648,thomasfischer@example.com
4,4636,Anthony Kelly,Marketing,107759,447305084431,lorraine66@example.net
...,...,...,...,...,...,...
95,1233,Rebecca Wilson,Legal,90301,384373966166,blackjohn@example.net
96,7272,Anthony Garrett,HR,89426,525950299572,sthomas@example.com
97,1413,Michelle Flores,Legal,279241,6604095460,jkelley@example.com
98,3303,Kimberly Washington,HR,89920,322357499530,diana78@example.org
99,1972,Jacob Carroll,HR,86867,66936628274,rcrawford@example.org

In [ ]:
df.to_csv("dataset/confidential/employees.csv", index=False)

In [ ]:
import os

print(os.getcwd())

/content

In [ ]:
import os

print(os.listdir("/content/dataset/confidential"))

['employees.csv']

In [ ]:
from google.colab import files

files.download("/content/dataset/confidential/employees.csv")

In [ ]:
def generate_employee():

    classification = random.choice([
        "Public",
        "Internal",
        "Confidential",
        "Restricted"
    ])

    risk = {
        "Public":"Low",
        "Internal":"Medium",
        "Confidential":"High",
        "Restricted":"Critical"
    }

    score = {
        "Public":random.randint(1,25),
        "Internal":random.randint(26,50),
        "Confidential":random.randint(51,80),
        "Restricted":random.randint(81,100)
    }

    employee = {

        "EmployeeID":fake.random_int(1000,9999),

        "Name":fake.name(),

        "Department":random.choice([
            "HR",
            "Finance",
            "IT",
            "Marketing",
            "Legal"
        ]),

        "Salary":random.randint(50000,300000),

        "NIC":fake.random_number(digits=12),

        "BankAccount":fake.random_number(digits=10),

        "Email":fake.email(),

        "DocumentType":"Employee Record",

        "Classification":classification,

        "RiskLevel":risk[classification],

        "LeakageScore":score[classification]

    }

    return employee

In [ ]:
employees=[]

for i in range(500):

    employees.append(generate_employee())

df=pd.DataFrame(employees)

df.head()

,EmployeeID,Name,Department,Salary,NIC,BankAccount,Email,DocumentType,Classification,RiskLevel,LeakageScore
0,5710,Sandra Torres,IT,257292,399038856244,9105228812,emmawagner@example.net,Employee Record,Public,Low,4
1,8203,Matthew Shaffer,HR,93898,401338969286,4044766671,mario50@example.net,Employee Record,Public,Low,1
2,3911,Sarah Martinez,Legal,159687,472655581321,2840714401,sherrigross@example.com,Employee Record,Confidential,High,75
3,4539,Timothy Collins,IT,287331,118288129107,9474623447,juansmith@example.org,Employee Record,Public,Low,12
4,2758,Jesse Baker,IT,259645,658032402722,4329429662,xbenton@example.com,Employee Record,Internal,Medium,30

In [ ]:
df.to_csv("SME_DLP_Dataset.csv",index=False)

print("Dataset Created Successfully")

Dataset Created Successfully

In [ ]:
df.sample(10)

,EmployeeID,Name,Department,Salary,NIC,BankAccount,Email,DocumentType,Classification,RiskLevel,LeakageScore
23,3814,David Torres,HR,51611,786153202822,5003664232,xwilliams@example.com,Employee Record,Restricted,Critical,83
90,5423,Ryan Santos,Finance,85417,438168654219,6944951149,melaniehayes@example.net,Employee Record,Public,Low,4
38,7555,John Garcia,Legal,203227,330619691293,394600319,derek87@example.com,Employee Record,Internal,Medium,30
136,7311,Damon Yu,Legal,140158,569254773350,9945982140,edward30@example.org,Employee Record,Public,Low,17
73,9729,Sydney Torres,Finance,166423,21396370268,6861666342,sherring@example.org,Employee Record,Internal,Medium,46
49,2828,Jonathan Cole,Legal,147650,110429559645,819839669,april71@example.com,Employee Record,Public,Low,12
152,8276,Chad Thomas,HR,99570,909468706590,8370091316,brownchase@example.com,Employee Record,Public,Low,4
367,5480,Dillon Brooks,Marketing,70671,786678227868,1881496157,lisarich@example.org,Employee Record,Restricted,Critical,97
201,1274,Christopher Wallace,HR,275262,682757492597,6869556495,mfritz@example.com,Employee Record,Restricted,Critical,86
468,9552,Robert Powell,Legal,237104,45858081913,9041475527,jenniferperry@example.com,Employee Record,Public,Low,23