<a href="https://colab.research.google.com/github/Osuni-99/Adaptive-AI-DLP-Research/blob/main/notebooks/04_Multimodal_Dataset_Generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install faker

Requirement already satisfied: faker in /usr/local/lib/python3.13/dist-packages (40.43.0)

In [ ]:
import random
import pandas as pd
from faker import Faker

fake = Faker()

print("Multimodal Dataset Generator Started")

Multimodal Dataset Generator Started

In [ ]:
!pip install -q faker python-docx reportlab openpyxl pillow pandas

In [ ]:
import random
import pandas as pd
from faker import Faker

fake = Faker()

print("Notebook 04 Started Successfully")

Notebook 04 Started Successfully

In [ ]:
DOCUMENTS = [

    {
        "DocumentType":"Employee Record",
        "Department":"HR",
        "Classification":"Confidential",
        "Formats":["TXT","DOCX","PDF","PNG"],
        "Risk":"High",
        "Indicators":["NIC","Employee ID","Email"]
    },

    {
        "DocumentType":"Salary Slip",
        "Department":"HR",
        "Classification":"Confidential",
        "Formats":["TXT","DOCX","PDF","PNG"],
        "Risk":"High",
        "Indicators":["Salary","NIC","Bank Account"]
    },

    {
        "DocumentType":"Invoice",
        "Department":"Finance",
        "Classification":"Internal",
        "Formats":["TXT","DOCX","PDF","PNG"],
        "Risk":"Medium",
        "Indicators":["Invoice","Amount"]
    },

    {
        "DocumentType":"Bank Statement",
        "Department":"Finance",
        "Classification":"Confidential",
        "Formats":["TXT","DOCX","PDF","PNG"],
        "Risk":"High",
        "Indicators":["Bank Account","Balance"]
    },

    {
        "DocumentType":"Contract",
        "Department":"Legal",
        "Classification":"Restricted",
        "Formats":["TXT","DOCX","PDF"],
        "Risk":"Critical",
        "Indicators":["Agreement","Contract"]
    }

]

template_df = pd.DataFrame(DOCUMENTS)

template_df

,DocumentType,Department,Classification,Formats,Risk,Indicators
0,Employee Record,HR,Confidential,"[TXT, DOCX, PDF, PNG]",High,"[NIC, Employee ID, Email]"
1,Salary Slip,HR,Confidential,"[TXT, DOCX, PDF, PNG]",High,"[Salary, NIC, Bank Account]"
2,Invoice,Finance,Internal,"[TXT, DOCX, PDF, PNG]",Medium,"[Invoice, Amount]"
3,Bank Statement,Finance,Confidential,"[TXT, DOCX, PDF, PNG]",High,"[Bank Account, Balance]"
4,Contract,Legal,Restricted,"[TXT, DOCX, PDF]",Critical,"[Agreement, Contract]"

In [ ]:
template_df.to_csv(
    "Document_Templates.csv",
    index=False
)

print("Templates Saved Successfully")

Templates Saved Successfully

In [ ]:
template_df

,DocumentType,Department,Classification,Formats,Risk,Indicators
0,Employee Record,HR,Confidential,"[TXT, DOCX, PDF, PNG]",High,"[NIC, Employee ID, Email]"
1,Salary Slip,HR,Confidential,"[TXT, DOCX, PDF, PNG]",High,"[Salary, NIC, Bank Account]"
2,Invoice,Finance,Internal,"[TXT, DOCX, PDF, PNG]",Medium,"[Invoice, Amount]"
3,Bank Statement,Finance,Confidential,"[TXT, DOCX, PDF, PNG]",High,"[Bank Account, Balance]"
4,Contract,Legal,Restricted,"[TXT, DOCX, PDF]",Critical,"[Agreement, Contract]"

In [ ]:
from docx import Document

In [ ]:
!pip install faker python-docx reportlab openpyxl pillow pandas

Requirement already satisfied: faker in /usr/local/lib/python3.13/dist-packages (40.43.0)
Requirement already satisfied: python-docx in /usr/local/lib/python3.13/dist-packages (1.2.0)
Requirement already satisfied: reportlab in /usr/local/lib/python3.13/dist-packages (5.0.1)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (11.3.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from python-docx) (6.1.3)
Requirement already satisfied: typing_extensions>=4.9.0 in /usr/local/lib/python3.13/dist-packages (from python-docx) (4.16.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.13/dist-packages (from reportlab) (3.4.9)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
from docx import Document

In [ ]:
employee = {

    "Company":"ABC Holdings (Pvt) Ltd",

    "Employee Name":fake.name(),

    "Employee ID":fake.random_int(1000,9999),

    "Department":"HR",

    "NIC":fake.random_number(digits=12),

    "Bank Account":fake.random_number(digits=10),

    "Basic Salary":random.randint(50000,250000),

    "Allowance":random.randint(5000,30000),

    "Tax":random.randint(1000,15000)

}

employee["Net Salary"]=(

employee["Basic Salary"]

+

employee["Allowance"]

-

employee["Tax"]

)

employee

{'Company': 'ABC Holdings (Pvt) Ltd',
 'Employee Name': 'Laura Hall',
 'Employee ID': 8640,
 'Department': 'HR',
 'NIC': 539271148325,
 'Bank Account': 4155500724,
 'Basic Salary': 104848,
 'Allowance': 23629,
 'Tax': 5555,
 'Net Salary': 122922}

In [ ]:
!pip install -q faker python-docx reportlab openpyxl pillow pandas

In [ ]:
import random
import pandas as pd

from faker import Faker
from docx import Document

fake = Faker()

print("All Libraries Loaded Successfully")

All Libraries Loaded Successfully

In [ ]:
employee = {

    "Company":"ABC Holdings (Pvt) Ltd",

    "Employee Name":fake.name(),

    "Employee ID":fake.random_int(1000,9999),

    "Department":"HR",

    "NIC":fake.random_number(digits=12),

    "Bank Account":fake.random_number(digits=10),

    "Basic Salary":random.randint(50000,250000),

    "Allowance":random.randint(5000,30000),

    "Tax":random.randint(1000,15000)

}

employee["Net Salary"] = (
    employee["Basic Salary"] +
    employee["Allowance"] -
    employee["Tax"]
)

employee

{'Company': 'ABC Holdings (Pvt) Ltd',
 'Employee Name': 'Emily Acevedo',
 'Employee ID': 9586,
 'Department': 'HR',
 'NIC': 695497775726,
 'Bank Account': 7920810215,
 'Basic Salary': 227166,
 'Allowance': 24838,
 'Tax': 10248,
 'Net Salary': 241756}

In [ ]:
import os

print(os.getcwd())

/content

In [ ]:
employee = {

    "Company":"ABC Holdings (Pvt) Ltd",

    "Employee Name":fake.name(),

    "Employee ID":fake.random_int(1000,9999),

    "Department":"HR",

    "NIC":fake.random_number(digits=12),

    "Bank Account":fake.random_number(digits=10),

    "Basic Salary":random.randint(50000,250000),

    "Allowance":random.randint(5000,30000),

    "Tax":random.randint(1000,15000)

}

employee["Net Salary"]=(

employee["Basic Salary"]

+

employee["Allowance"]

-

employee["Tax"]

)

employee

{'Company': 'ABC Holdings (Pvt) Ltd',
 'Employee Name': 'Joan Duarte',
 'Employee ID': 4835,
 'Department': 'HR',
 'NIC': 134704310259,
 'Bank Account': 3729318679,
 'Basic Salary': 166856,
 'Allowance': 23287,
 'Tax': 12471,
 'Net Salary': 177672}

In [ ]:
doc=Document()

doc.add_heading("Salary Slip",0)

for key,value in employee.items():

    doc.add_paragraph(f"{key} : {value}")

doc.save("Salary_Slip_001.docx")

print("DOCX Generated Successfully")

DOCX Generated Successfully

In [ ]:
import os

os.listdir()

['.config',
 'Salary_Slip',
 'Salary_Slip_001.docx',
 'Salary_Slip.docx',
 'dataset_metadata.csv',
 'Contract.docx',
 'Invoice.docx',
 'Document_Templates.csv',
 'test.docx',
 'sample_data']

In [ ]:
from docx import Document

def generate_document(document_type, data):

    doc = Document()

    doc.add_heading(document_type, level=1)

    for key, value in data.items():
        doc.add_paragraph(f"{key}: {value}")

    filename = document_type.replace(" ", "_") + ".docx"

    doc.save(filename)

    print(f"{filename} Generated Successfully")

    return filename

In [ ]:
!pip show python-docx

Name: python-docx
Version: 1.2.0
Summary: Create, read, and update Microsoft Word .docx files.
Home-page: https://github.com/python-openxml/python-docx
Author:
Author-email: Steve Canny <stcanny@gmail.com>
License: MIT
Location: /usr/local/lib/python3.13/dist-packages
Requires: lxml, typing_extensions
Required-by:

In [ ]:
!pip list | grep docx

python-docx                           1.2.0

In [ ]:
!pip install python-docx

Requirement already satisfied: python-docx in /usr/local/lib/python3.13/dist-packages (1.2.0)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from python-docx) (6.1.3)
Requirement already satisfied: typing_extensions>=4.9.0 in /usr/local/lib/python3.13/dist-packages (from python-docx) (4.16.0)

In [ ]:
!pip show python-docx

Name: python-docx
Version: 1.2.0
Summary: Create, read, and update Microsoft Word .docx files.
Home-page: https://github.com/python-openxml/python-docx
Author:
Author-email: Steve Canny <stcanny@gmail.com>
License: MIT
Location: /usr/local/lib/python3.13/dist-packages
Requires: lxml, typing_extensions
Required-by:

In [ ]:
!pip list | grep docx

python-docx                           1.2.0

In [ ]:
import docx

print(docx.__version__)

1.2.0

In [ ]:
from docx import Document

doc = Document()

doc.add_heading("Test Document", level=1)

doc.add_paragraph("This is a test.")

doc.save("test.docx")

print("Success")

Success

In [ ]:
!pip install -q faker python-docx reportlab openpyxl pillow pandas

In [ ]:
import random
import pandas as pd
from faker import Faker
from docx import Document

fake = Faker()

In [ ]:
!pip install -q faker python-docx reportlab openpyxl pillow pandas

In [ ]:
# Install Libraries
!pip install -q faker python-docx reportlab openpyxl pillow pandas

# Imports
import random
import pandas as pd
from faker import Faker
from docx import Document

fake = Faker()

print("Notebook Ready")

Notebook Ready

In [ ]:
from docx import Document

def generate_document(document_type, data):

    doc = Document()

    doc.add_heading(document_type, level=1)

    for key, value in data.items():
        doc.add_paragraph(f"{key}: {value}")

    filename = document_type.replace(" ", "_") + ".docx"

    doc.save(filename)

    print(f"{filename} Generated Successfully")

    return filename

In [ ]:
salary_data = {

    "Company":"ABC Holdings (Pvt) Ltd",

    "Employee Name":fake.name(),

    "Employee ID":fake.random_int(1000,9999),

    "Department":"HR",

    "NIC":fake.random_number(digits=12),

    "Bank Account":fake.random_number(digits=10),

    "Basic Salary":random.randint(50000,250000),

    "Allowance":random.randint(5000,30000),

    "Tax":random.randint(1000,15000)

}

salary_data["Net Salary"] = (
    salary_data["Basic Salary"]
    + salary_data["Allowance"]
    - salary_data["Tax"]
)

generate_document(
    "Salary Slip",
    salary_data
)

Salary_Slip.docx Generated Successfully

'Salary_Slip.docx'

In [ ]:
invoice_data = {

    "Invoice Number":"INV-2026-001",

    "Customer Name":fake.name(),

    "Amount":random.randint(10000,500000),

    "Tax":random.randint(1000,50000),

    "Invoice Date":fake.date()

}

generate_document(
    "Invoice",
    invoice_data
)

Invoice.docx Generated Successfully

'Invoice.docx'

In [ ]:
contract_data = {

    "Contract Number":"CNT-2026-1001",

    "Client":fake.name(),

    "Agreement Date":fake.date(),

    "Contract Value":random.randint(100000,1000000)

}

generate_document(
    "Contract",
    contract_data
)

Contract.docx Generated Successfully

'Contract.docx'

In [ ]:
import os

files = [f for f in os.listdir() if f.endswith(".docx")]

files

['Salary_Slip_001.docx',
 'Salary_Slip.docx',
 'Contract.docx',
 'Invoice.docx',
 'test.docx']

In [ ]:
def create_salary_data():

    data = {

        "Company":"ABC Holdings (Pvt) Ltd",

        "Employee Name":fake.name(),

        "Employee ID":fake.random_int(1000,9999),

        "Department":"HR",

        "NIC":fake.random_number(digits=12),

        "Bank Account":fake.random_number(digits=10),

        "Basic Salary":random.randint(50000,250000),

        "Allowance":random.randint(5000,30000),

        "Tax":random.randint(1000,15000)

    }

    data["Net Salary"] = (
        data["Basic Salary"]
        + data["Allowance"]
        - data["Tax"]
    )

    return data

In [ ]:
def create_invoice_data():

    return {

        "Invoice Number":f"INV-{fake.random_int(1000,9999)}",

        "Customer Name":fake.name(),

        "Amount":random.randint(10000,500000),

        "Tax":random.randint(1000,30000),

        "Invoice Date":fake.date()

    }

In [ ]:
def create_contract_data():

    return {

        "Contract Number":f"CNT-{fake.random_int(1000,9999)}",

        "Client":fake.name(),

        "Agreement Date":fake.date(),

        "Contract Value":random.randint(100000,1000000)

    }

In [ ]:
def generate_bulk_documents(document_type, count):

    for i in range(1, count + 1):

        if document_type == "Salary Slip":
            data = create_salary_data()

        elif document_type == "Invoice":
            data = create_invoice_data()

        elif document_type == "Contract":
            data = create_contract_data()

        else:
            print("Unknown Document Type")
            return

        filename = generate_document(document_type, data)

    print(f"{count} {document_type} documents generated successfully.")

In [ ]:
generate_bulk_documents(
    "Salary Slip",
    5
)

Salary_Slip.docx Generated Successfully
Salary_Slip.docx Generated Successfully
Salary_Slip.docx Generated Successfully
Salary_Slip.docx Generated Successfully
Salary_Slip.docx Generated Successfully
5 Salary Slip documents generated successfully.

In [ ]:
from docx import Document
import os

def generate_document(document_type, data, file_number):

    doc = Document()

    doc.add_heading(document_type, level=1)

    for key, value in data.items():
        doc.add_paragraph(f"{key}: {value}")

    folder = document_type.replace(" ", "_")

    os.makedirs(folder, exist_ok=True)

    filename = f"{folder}/{folder}_{file_number:03d}.docx"

    doc.save(filename)

    return filename

In [ ]:
def generate_bulk_documents(document_type, count):

    generated_files = []

    for i in range(1, count + 1):

        if document_type == "Salary Slip":
            data = create_salary_data()

        elif document_type == "Invoice":
            data = create_invoice_data()

        elif document_type == "Contract":
            data = create_contract_data()

        else:
            print("Unknown Document Type")
            return []

        filename = generate_document(
            document_type,
            data,
            i
        )

        generated_files.append(filename)

    print(f"{count} {document_type} documents generated.")

    return generated_files

In [ ]:
salary_files = generate_bulk_documents(
    "Salary Slip",
    10
)

salary_files

10 Salary Slip documents generated.

['Salary_Slip/Salary_Slip_001.docx',
 'Salary_Slip/Salary_Slip_002.docx',
 'Salary_Slip/Salary_Slip_003.docx',
 'Salary_Slip/Salary_Slip_004.docx',
 'Salary_Slip/Salary_Slip_005.docx',
 'Salary_Slip/Salary_Slip_006.docx',
 'Salary_Slip/Salary_Slip_007.docx',
 'Salary_Slip/Salary_Slip_008.docx',
 'Salary_Slip/Salary_Slip_009.docx',
 'Salary_Slip/Salary_Slip_010.docx']

In [ ]:
import os

os.listdir("Salary_Slip")

['Salary_Slip_006.docx',
 'Salary_Slip_007.docx',
 'Salary_Slip_010.docx',
 'Salary_Slip_005.docx',
 'Salary_Slip_001.docx',
 'Salary_Slip_004.docx',
 'Salary_Slip_008.docx',
 'Salary_Slip_009.docx',
 'Salary_Slip_003.docx',
 'Salary_Slip_002.docx']

In [ ]:
metadata = []

In [ ]:
def generate_bulk_documents(document_type, count):

    generated_files = []

    for i in range(1, count + 1):

        if document_type == "Salary Slip":

            data = create_salary_data()

            department = "HR"

            classification = "Confidential"

            risk = "High"

        elif document_type == "Invoice":

            data = create_invoice_data()

            department = "Finance"

            classification = "Internal"

            risk = "Medium"

        elif document_type == "Contract":

            data = create_contract_data()

            department = "Legal"

            classification = "Restricted"

            risk = "Critical"

        else:

            continue

        filename = generate_document(
            document_type,
            data,
            i
        )

        generated_files.append(filename)

        metadata.append({

            "File":filename,

            "DocumentType":document_type,

            "Department":department,

            "Classification":classification,

            "Risk":risk

        })

    return generated_files

In [ ]:
metadata = []

generate_bulk_documents("Salary Slip",10)

generate_bulk_documents("Invoice",10)

generate_bulk_documents("Contract",10)

['Contract/Contract_001.docx',
 'Contract/Contract_002.docx',
 'Contract/Contract_003.docx',
 'Contract/Contract_004.docx',
 'Contract/Contract_005.docx',
 'Contract/Contract_006.docx',
 'Contract/Contract_007.docx',
 'Contract/Contract_008.docx',
 'Contract/Contract_009.docx',
 'Contract/Contract_010.docx']

In [ ]:

def create_invoice_data():
    return {
        "Invoice Number": f"INV-{fake.random_int(1000, 9999)}",
        "Customer Name": fake.name(),
        "Amount": random.randint(10000, 500000),
        "Tax": random.randint(1000, 30000),
        "Invoice Date": fake.date()
    }


def generate_bulk_documents(document_type, count):
    for i in range(1, count + 1):

        if document_type == "Salary Slip":
            data = create_salary_data()

        elif document_type == "Invoice":
            data = create_invoice_data()

        elif document_type == "Contract":
            data = create_contract_data()

        else:
            print("Unknown Document Type")
            return

        filename = generate_document(document_type, data)

    print(f"{count} {document_type} documents generated successfully.")

In [ ]:
metadata_df = pd.DataFrame(metadata)

metadata_df

,File,DocumentType,Department,Classification,Risk
0,Salary_Slip/Salary_Slip_001.docx,Salary Slip,HR,Confidential,High
1,Salary_Slip/Salary_Slip_002.docx,Salary Slip,HR,Confidential,High
2,Salary_Slip/Salary_Slip_003.docx,Salary Slip,HR,Confidential,High
3,Salary_Slip/Salary_Slip_004.docx,Salary Slip,HR,Confidential,High
4,Salary_Slip/Salary_Slip_005.docx,Salary Slip,HR,Confidential,High
5,Salary_Slip/Salary_Slip_006.docx,Salary Slip,HR,Confidential,High
6,Salary_Slip/Salary_Slip_007.docx,Salary Slip,HR,Confidential,High
7,Salary_Slip/Salary_Slip_008.docx,Salary Slip,HR,Confidential,High
8,Salary_Slip/Salary_Slip_009.docx,Salary Slip,HR,Confidential,High
9,Salary_Slip/Salary_Slip_010.docx,Salary Slip,HR,Confidential,High
10,Invoice/Invoice_001.docx,Invoice,Finance,Internal,Medium
11,Invoice/Invoice_002.docx,Invoice,Finance,Internal,Medium
12,Invoice/Invoice_003.docx,Invoice,Finance,Internal,Medium
13,Invoice/Invoice_004.docx,Invoice,Finance,Internal,Medium
14,Invoice/Invoice_005.docx,Invoice,Finance,Internal,Medium
15,Invoice/Invoice_006.docx,Invoice,Finance,Internal,Medium
16,Invoice/Invoice_007.docx,Invoice,Finance,Internal,Medium
17,Invoice/Invoice_008.docx,Invoice,Finance,Internal,Medium
18,Invoice/Invoice_009.docx,Invoice,Finance,Internal,Medium
19,Invoice/Invoice_010.docx,Invoice,Finance,Internal,Medium
20,Contract/Contract_001.docx,Contract,Legal,Restricted,Critical
21,Contract/Contract_002.docx,Contract,Legal,Restricted,Critical
22,Contract/Contract_003.docx,Contract,Legal,Restricted,Critical
23,Contract/Contract_004.docx,Contract,Legal,Restricted,Critical
24,Contract/Contract_005.docx,Contract,Legal,Restricted,Critical
25,Contract/Contract_006.docx,Contract,Legal,Restricted,Critical
26,Contract/Contract_007.docx,Contract,Legal,Restricted,Critical
27,Contract/Contract_008.docx,Contract,Legal,Restricted,Critical
28,Contract/Contract_009.docx,Contract,Legal,Restricted,Critical
29,Contract/Contract_010.docx,Contract,Legal,Restricted,Critical

In [ ]:
metadata_df.to_csv(

    "dataset_metadata.csv",

    index=False

)

print("Metadata Saved Successfully")

Metadata Saved Successfully

In [ ]:
!pip install -q reportlab pillow

In [ ]:
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet

from PIL import Image, ImageDraw
import os

In [ ]:
def export_txt(data, filename):

    with open(filename, "w") as f:

        for key, value in data.items():

            f.write(f"{key}: {value}\n")

    print(filename, "Created")

In [ ]:
def export_pdf(data, filename):

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    story.append(Paragraph("<b>Generated Document</b>", styles["Heading1"]))

    for key, value in data.items():

        story.append(
            Paragraph(f"<b>{key}</b>: {value}", styles["Normal"])
        )

    doc.build(story)

    print(filename, "Created")

In [ ]:
def export_png(data, filename):

    image = Image.new("RGB", (800, 900), "white")

    draw = ImageDraw.Draw(image)

    y = 30

    draw.text((20, 10), "Generated Document", fill="black")

    for key, value in data.items():

        draw.text((20, y), f"{key}: {value}", fill="black")

        y += 30

    image.save(filename)

    print(filename, "Created")

In [ ]:
def export_document(data, document_type, number):

    folder = document_type.replace(" ", "_")

    os.makedirs(folder, exist_ok=True)

    base = f"{folder}/{folder}_{number:03d}"

    # TXT
    export_txt(data, base + ".txt")

    # DOCX
    generate_document(document_type, data, number)

    # PDF
    export_pdf(data, base + ".pdf")

    # PNG
    export_png(data, base + ".png")

In [ ]:
salary_data = create_salary_data()

export_document(
    salary_data,
    "Salary Slip",
    1
)

Salary_Slip/Salary_Slip_001.txt Created
Salary_Slip/Salary_Slip_001.pdf Created
Salary_Slip/Salary_Slip_001.png Created

In [ ]:
export_document(
    create_invoice_data(),
    "Invoice",
    1
)

Invoice/Invoice_001.txt Created
Invoice/Invoice_001.pdf Created
Invoice/Invoice_001.png Created

In [ ]:
import os

print(os.listdir("Salary_Slip"))

['Salary_Slip_006.docx', 'Salary_Slip_007.docx', 'Salary_Slip_010.docx', 'Salary_Slip_005.docx', 'Salary_Slip_001.docx', 'Salary_Slip_004.docx', 'Salary_Slip_001.png', 'Salary_Slip_001.txt', 'Salary_Slip_008.docx', 'Salary_Slip_009.docx', 'Salary_Slip_003.docx', 'Salary_Slip_001.pdf', 'Salary_Slip_002.docx']

In [ ]:
from docx import Document
import os

def generate_document(document_type, data, file_number):

    doc = Document()

    doc.add_heading(document_type, level=1)

    for key, value in data.items():
        doc.add_paragraph(f"{key}: {value}")

    folder = document_type.replace(" ", "_")

    os.makedirs(folder, exist_ok=True)

    filename = f"{folder}/{folder}_{file_number:03d}.docx"

    doc.save(filename)

    print(filename, "Created")

    return filename

In [ ]:
salary_data = create_salary_data()

export_document(
    salary_data,
    "Salary Slip",
    2
)

Salary_Slip/Salary_Slip_002.txt Created
Salary_Slip/Salary_Slip_002.docx Created
Salary_Slip/Salary_Slip_002.pdf Created
Salary_Slip/Salary_Slip_002.png Created

In [ ]:
def create_bank_statement_data():

    transactions = []

    for i in range(5):

        transactions.append({

            "Date": fake.date(),

            "Description": random.choice([
                "Salary Credit",
                "ATM Withdrawal",
                "Online Transfer",
                "Utility Payment",
                "POS Purchase"
            ]),

            "Amount": random.randint(1000,50000)

        })

    return {

        "Bank Name":"ABC Bank PLC",

        "Account Holder":fake.name(),

        "Account Number":fake.random_number(digits=10),

        "Branch":random.choice([
            "Colombo",
            "Galle",
            "Kandy",
            "Matara"
        ]),

        "Current Balance":random.randint(50000,1000000),

        "Transactions":transactions

    }

In [ ]:
bank_data = create_bank_statement_data()

bank_data

{'Bank Name': 'ABC Bank PLC',
 'Account Holder': 'Mark Smith',
 'Account Number': 4067236110,
 'Branch': 'Galle',
 'Current Balance': 623829,
 'Transactions': [{'Date': '1973-07-15',
   'Description': 'Utility Payment',
   'Amount': 40905},
  {'Date': '2020-05-07', 'Description': 'POS Purchase', 'Amount': 38134},
  {'Date': '1972-10-10', 'Description': 'Online Transfer', 'Amount': 10529},
  {'Date': '1999-06-23', 'Description': 'Online Transfer', 'Amount': 43318},
  {'Date': '2015-01-14', 'Description': 'Utility Payment', 'Amount': 23676}]}

In [ ]:
export_document(

    bank_data,

    "Bank Statement",

    1

)

Bank_Statement/Bank_Statement_001.txt Created
Bank_Statement/Bank_Statement_001.docx Created
Bank_Statement/Bank_Statement_001.pdf Created
Bank_Statement/Bank_Statement_001.png Created

In [ ]:
import os

os.listdir("Bank_Statement")

['Bank_Statement_001.pdf',
 'Bank_Statement_001.docx',
 'Bank_Statement_001.png',
 'Bank_Statement_001.txt']

In [ ]:
def create_bank_statement_data():

    transactions = []

    for i in range(5):

        transactions.append([

            fake.date(),

            random.choice([
                "Salary Credit",
                "ATM Withdrawal",
                "POS Purchase",
                "Online Transfer",
                "Utility Payment"
            ]),

            random.randint(1000,50000)

        ])

    return {

        "Bank Name":"ABC Bank PLC",

        "Account Holder":fake.name(),

        "Account Number":str(fake.random_number(digits=10)),

        "Branch":random.choice([
            "Colombo",
            "Galle",
            "Matara",
            "Kandy"
        ]),

        "Current Balance":random.randint(50000,1000000),

        "Transactions":transactions

    }

In [ ]:
bank_data = create_bank_statement_data()

bank_data

{'Bank Name': 'ABC Bank PLC',
 'Account Holder': 'Michael Erickson',
 'Account Number': '584885819',
 'Branch': 'Colombo',
 'Current Balance': 856256,
 'Transactions': [['1987-05-18', 'Online Transfer', 4665],
  ['1976-08-01', 'Salary Credit', 29888],
  ['2007-02-12', 'POS Purchase', 35894],
  ['2002-10-05', 'POS Purchase', 21139],
  ['2019-04-22', 'Utility Payment', 30124]]}

In [ ]:
from docx import Document
from docx.shared import Pt

def generate_bank_statement(data, number):

    doc = Document()

    doc.add_heading(
        data["Bank Name"],
        level=1
    )

    doc.add_heading(
        "BANK STATEMENT",
        level=2
    )

    doc.add_paragraph(
        f"Account Holder : {data['Account Holder']}"
    )

    doc.add_paragraph(
        f"Account Number : {data['Account Number']}"
    )

    doc.add_paragraph(
        f"Branch : {data['Branch']}"
    )

    doc.add_paragraph(
        f"Current Balance : Rs.{data['Current Balance']}"
    )

    doc.add_heading(
        "Transactions",
        level=2
    )

    table = doc.add_table(
        rows=1,
        cols=3
    )

    table.style = "Table Grid"

    hdr = table.rows[0].cells

    hdr[0].text = "Date"

    hdr[1].text = "Description"

    hdr[2].text = "Amount"

    for row in data["Transactions"]:

        cells = table.add_row().cells

        cells[0].text = str(row[0])

        cells[1].text = row[1]

        cells[2].text = str(row[2])

    folder = "Bank_Statement"

    import os

    os.makedirs(folder,exist_ok=True)

    filename = f"{folder}/Bank_Statement_{number:03d}.docx"

    doc.save(filename)

    print(filename,"Created")

In [ ]:
generate_bank_statement(
    bank_data,
    1
)

Bank_Statement/Bank_Statement_001.docx Created

In [ ]:
import os

os.listdir("Bank_Statement")

['Bank_Statement_001.pdf',
 'Bank_Statement_001.docx',
 'Bank_Statement_001.png',
 'Bank_Statement_001.txt']

In [ ]:
import os

os.makedirs("templates", exist_ok=True)

print("Templates Folder Created")

Templates Folder Created

In [ ]:
import json

salary_template = {

    "DocumentType":"Salary Slip",

    "Department":"HR",

    "Classification":"Confidential",

    "Fields":[

        "Company",
        "Employee Name",
        "Employee ID",
        "Department",
        "NIC",
        "Bank Account",
        "Basic Salary",
        "Allowance",
        "Tax",
        "Net Salary"

    ]
}

with open("templates/salary_slip.json","w") as f:

    json.dump(salary_template,f,indent=4)

print("Salary Template Saved")

Salary Template Saved

In [ ]:
invoice_template = {

    "DocumentType":"Invoice",

    "Department":"Finance",

    "Classification":"Internal",

    "Fields":[

        "Invoice Number",
        "Customer Name",
        "Amount",
        "Tax",
        "Invoice Date"

    ]
}

with open("templates/invoice.json","w") as f:

    json.dump(invoice_template,f,indent=4)

print("Invoice Template Saved")

Invoice Template Saved

In [ ]:
contract_template = {

    "DocumentType":"Contract",

    "Department":"Legal",

    "Classification":"Restricted",

    "Fields":[

        "Contract Number",
        "Client",
        "Agreement Date",
        "Contract Value"

    ]
}

with open("templates/contract.json","w") as f:

    json.dump(contract_template,f,indent=4)

print("Contract Template Saved")

Contract Template Saved

In [ ]:
bank_template = {

    "DocumentType":"Bank Statement",

    "Department":"Finance",

    "Classification":"Confidential",

    "Fields":[

        "Bank Name",
        "Account Holder",
        "Account Number",
        "Branch",
        "Current Balance",
        "Transactions"

    ]
}

with open("templates/bank_statement.json","w") as f:

    json.dump(bank_template,f,indent=4)

print("Bank Statement Template Saved")

Bank Statement Template Saved

In [ ]:
os.listdir("templates")

['bank_statement.json', 'salary_slip.json', 'contract.json', 'invoice.json']

In [ ]:
import json

def load_template(template_name):

    path = f"templates/{template_name}"

    with open(path, "r") as file:

        template = json.load(file)

    return template

In [ ]:
salary_template = load_template("salary_slip.json")

salary_template

{'DocumentType': 'Salary Slip',
 'Department': 'HR',
 'Classification': 'Confidential',
 'Fields': ['Company',
  'Employee Name',
  'Employee ID',
  'Department',
  'NIC',
  'Bank Account',
  'Basic Salary',
  'Allowance',
  'Tax',
  'Net Salary']}

In [ ]:
def generate_document_from_template(template_name, data, number):

    template = load_template(template_name)

    document_type = template["DocumentType"]

    export_document(
        data,
        document_type,
        number
    )

    print(f"{document_type} Generated Successfully")

In [ ]:
salary_data = create_salary_data()

generate_document_from_template(

    "salary_slip.json",

    salary_data,

    2

)

Salary_Slip/Salary_Slip_002.txt Created
Salary_Slip/Salary_Slip_002.docx Created
Salary_Slip/Salary_Slip_002.pdf Created
Salary_Slip/Salary_Slip_002.png Created
Salary Slip Generated Successfully

In [ ]:
invoice_data = create_invoice_data()

generate_document_from_template(

    "invoice.json",

    invoice_data,

    2

)

Invoice/Invoice_002.txt Created
Invoice/Invoice_002.docx Created
Invoice/Invoice_002.pdf Created
Invoice/Invoice_002.png Created
Invoice Generated Successfully

In [ ]:
bank_data = create_bank_statement_data()

generate_document_from_template(

    "bank_statement.json",

    bank_data,

    2

)

Bank_Statement/Bank_Statement_002.txt Created
Bank_Statement/Bank_Statement_002.docx Created
Bank_Statement/Bank_Statement_002.pdf Created
Bank_Statement/Bank_Statement_002.png Created
Bank Statement Generated Successfully

In [ ]:
leave_form_template = {

    "DocumentType":"Leave Form",

    "Department":"HR",

    "Classification":"Internal",

    "Fields":[

        "Company",
        "Employee Name",
        "Employee ID",
        "Department",
        "Leave Type",
        "From Date",
        "To Date",
        "Reason",
        "Approved By"

    ]
}

with open("templates/leave_form.json","w") as f:

    json.dump(leave_form_template,f,indent=4)

print("Leave Form Template Saved")

Leave Form Template Saved

In [ ]:
hr_policy_template = {

    "DocumentType":"HR Policy",

    "Department":"HR",

    "Classification":"Internal",

    "Fields":[

        "Company",
        "Policy Number",
        "Policy Name",
        "Effective Date",
        "Review Date",
        "Approved By"

    ]
}

with open("templates/hr_policy.json","w") as f:

    json.dump(hr_policy_template,f,indent=4)

print("HR Policy Template Saved")

HR Policy Template Saved

In [ ]:
def create_leave_form_data():

    return {

        "Company":"ABC Holdings (Pvt) Ltd",

        "Employee Name":fake.name(),

        "Employee ID":f"EMP-{fake.random_int(1000,9999)}",

        "Department":random.choice([
            "HR","Finance","IT","Marketing"
        ]),

        "Leave Type":random.choice([
            "Annual Leave",
            "Medical Leave",
            "Casual Leave",
            "Maternity Leave"
        ]),

        "From Date":fake.date(),

        "To Date":fake.date(),

        "Reason":random.choice([
            "Medical",
            "Vacation",
            "Personal",
            "Family Event"
        ]),

        "Approved By":"HR Manager"

    }

In [ ]:
def create_hr_policy_data():

    return {

        "Company":"ABC Holdings (Pvt) Ltd",

        "Policy Number":f"HR-{fake.random_int(100,999)}",

        "Policy Name":random.choice([

            "Leave Policy",
            "Remote Work Policy",
            "Attendance Policy",
            "Code of Conduct"

        ]),

        "Effective Date":fake.date(),

        "Review Date":fake.date(),

        "Approved By":"Head of Human Resources"

    }

In [ ]:
leave_data = create_leave_form_data()

generate_document_from_template(

    "leave_form.json",

    leave_data,

    1

)

Leave_Form/Leave_Form_001.txt Created
Leave_Form/Leave_Form_001.docx Created
Leave_Form/Leave_Form_001.pdf Created
Leave_Form/Leave_Form_001.png Created
Leave Form Generated Successfully

In [ ]:
policy_data = create_hr_policy_data()

generate_document_from_template(

    "hr_policy.json",

    policy_data,

    1

)

HR_Policy/HR_Policy_001.txt Created
HR_Policy/HR_Policy_001.docx Created
HR_Policy/HR_Policy_001.pdf Created
HR_Policy/HR_Policy_001.png Created
HR Policy Generated Successfully

In [ ]:
import os

print(os.listdir("Leave_Form"))

print(os.listdir("HR_Policy"))

['Leave_Form_001.docx', 'Leave_Form_001.txt', 'Leave_Form_001.png', 'Leave_Form_001.pdf']
['HR_Policy_001.png', 'HR_Policy_001.pdf', 'HR_Policy_001.txt', 'HR_Policy_001.docx']

In [ ]:
meeting_template = {

    "DocumentType": "Meeting Minutes",

    "Department": "Operations",

    "Classification": "Internal",

    "Fields": [

        "Company",
        "Meeting ID",
        "Meeting Date",
        "Meeting Time",
        "Location",
        "Chairperson",
        "Attendees",
        "Agenda",
        "Discussion",
        "Action Items"

    ]
}

with open("templates/meeting_minutes.json","w") as f:

    json.dump(meeting_template,f,indent=4)

print("Meeting Minutes Template Saved")

Meeting Minutes Template Saved

In [ ]:
def create_meeting_minutes_data():

    return {

        "Company":"ABC Holdings (Pvt) Ltd",

        "Meeting ID":f"MT-{fake.random_int(1000,9999)}",

        "Meeting Date":fake.date(),

        "Meeting Time":"10:00 AM",

        "Location":random.choice([

            "Board Room",
            "Conference Hall",
            "Meeting Room A"

        ]),

        "Chairperson":fake.name(),

        "Attendees":", ".join(fake.name() for _ in range(5)),

        "Agenda":"Quarterly Business Review",

        "Discussion":"Reviewed departmental performance and future action plans.",

        "Action Items":"Prepare implementation report before next meeting."

    }

In [ ]:
meeting_data = create_meeting_minutes_data()

generate_document_from_template(

    "meeting_minutes.json",

    meeting_data,

    1

)

Meeting_Minutes/Meeting_Minutes_001.txt Created
Meeting_Minutes/Meeting_Minutes_001.docx Created
Meeting_Minutes/Meeting_Minutes_001.pdf Created
Meeting_Minutes/Meeting_Minutes_001.png Created
Meeting Minutes Generated Successfully

In [ ]:
nda_template = {

    "DocumentType":"NDA",

    "Department":"Legal",

    "Classification":"Restricted",

    "Fields":[

        "Company",

        "Client",

        "Agreement Number",

        "Effective Date",

        "Expiry Date",

        "Confidential Information",

        "Authorized Signatory"

    ]
}

with open("templates/nda.json","w") as f:

    json.dump(nda_template,f,indent=4)

print("NDA Template Saved")

NDA Template Saved

In [ ]:
def create_nda_data():

    return {

        "Company":"ABC Holdings (Pvt) Ltd",

        "Client":fake.company(),

        "Agreement Number":f"NDA-{fake.random_int(1000,9999)}",

        "Effective Date":fake.date(),

        "Expiry Date":fake.date(),

        "Confidential Information":"Business plans, financial records and customer information.",

        "Authorized Signatory":fake.name()

    }

In [ ]:
nda_data = create_nda_data()

generate_document_from_template(

    "nda.json",

    nda_data,

    1

)

NDA/NDA_001.txt Created
NDA/NDA_001.docx Created
NDA/NDA_001.pdf Created
NDA/NDA_001.png Created
NDA Generated Successfully

In [ ]:
tax_template = {

    "DocumentType":"Tax Report",

    "Department":"Finance",

    "Classification":"Confidential",

    "Fields":[

        "Company",

        "TIN",

        "Financial Year",

        "Revenue",

        "Expenses",

        "Tax Amount"

    ]
}

with open("templates/tax_report.json","w") as f:

    json.dump(tax_template,f,indent=4)

print("Tax Report Template Saved")

Tax Report Template Saved

In [ ]:
def create_tax_report_data():

    return {

        "Company":"ABC Holdings (Pvt) Ltd",

        "TIN":fake.random_number(digits=9),

        "Financial Year":"2025/2026",

        "Revenue":random.randint(1000000,5000000),

        "Expenses":random.randint(500000,3000000),

        "Tax Amount":random.randint(100000,500000)

    }

In [ ]:
tax_data = create_tax_report_data()

generate_document_from_template(

    "tax_report.json",

    tax_data,

    1

)

Tax_Report/Tax_Report_001.txt Created
Tax_Report/Tax_Report_001.docx Created
Tax_Report/Tax_Report_001.pdf Created
Tax_Report/Tax_Report_001.png Created
Tax Report Generated Successfully

In [ ]:
firewall_template = {

    "DocumentType":"Firewall Configuration",

    "Department":"IT",

    "Classification":"Restricted",

    "Fields":[

        "Firewall Name",
        "Device IP",
        "Administrator",
        "VPN Status",
        "Allowed Ports",
        "Blocked IPs"

    ]
}

with open("templates/firewall_configuration.json","w") as f:

    json.dump(firewall_template,f,indent=4)

print("Firewall Configuration Template Saved")

Firewall Configuration Template Saved

In [ ]:
def create_firewall_configuration_data():

    return {

        "Firewall Name":"FortiGate 100F",

        "Device IP":fake.ipv4(),

        "Administrator":"Network Admin",

        "VPN Status":random.choice(["Enabled","Disabled"]),

        "Allowed Ports":"80,443,22",

        "Blocked IPs":f"{fake.ipv4()}, {fake.ipv4()}"

    }

In [ ]:
firewall_data = create_firewall_configuration_data()

generate_document_from_template(

    "firewall_configuration.json",

    firewall_data,

    1

)

Firewall_Configuration/Firewall_Configuration_001.txt Created
Firewall_Configuration/Firewall_Configuration_001.docx Created
Firewall_Configuration/Firewall_Configuration_001.pdf Created
Firewall_Configuration/Firewall_Configuration_001.png Created
Firewall Configuration Generated Successfully

In [ ]:
source_code_template = {

    "DocumentType":"Source Code",

    "Department":"IT",

    "Classification":"Restricted",

    "Fields":[

        "Project Name",
        "Programming Language",
        "API Key",
        "Database URL",
        "Repository",
        "Developer"

    ]
}

with open("templates/source_code.json","w") as f:

    json.dump(source_code_template,f,indent=4)

print("Source Code Template Saved")

Source Code Template Saved

In [ ]:
def create_source_code_data():

    return {

        "Project Name":"Adaptive AI DLP",

        "Programming Language":"Python",

        "API Key":fake.sha1(),

        "Database URL":"mysql://localhost:3306/dlp",

        "Repository":"Internal Git",

        "Developer":fake.name()

    }

In [ ]:
source_data = create_source_code_data()

generate_document_from_template(

    "source_code.json",

    source_data,

    1

)

Source_Code/Source_Code_001.txt Created
Source_Code/Source_Code_001.docx Created
Source_Code/Source_Code_001.pdf Created
Source_Code/Source_Code_001.png Created
Source Code Generated Successfully

In [ ]:
marketing_template = {

    "DocumentType":"Marketing Brochure",

    "Department":"Marketing",

    "Classification":"Public",

    "Fields":[

        "Company",

        "Campaign",

        "Product",

        "Description",

        "Contact"

    ]
}

with open("templates/marketing_brochure.json","w") as f:

    json.dump(marketing_template,f,indent=4)

print("Marketing Brochure Template Saved")

Marketing Brochure Template Saved

In [ ]:
def create_marketing_brochure_data():

    return {

        "Company":"ABC Holdings (Pvt) Ltd",

        "Campaign":"Digital Transformation 2026",

        "Product":"Secure Cloud Suite",

        "Description":"Enterprise security solution for SMEs.",

        "Contact":fake.phone_number()

    }

In [ ]:
marketing_data = create_marketing_brochure_data()

generate_document_from_template(

    "marketing_brochure.json",

    marketing_data,

    1

)

Marketing_Brochure/Marketing_Brochure_001.txt Created
Marketing_Brochure/Marketing_Brochure_001.docx Created
Marketing_Brochure/Marketing_Brochure_001.pdf Created
Marketing_Brochure/Marketing_Brochure_001.png Created
Marketing Brochure Generated Successfully

In [ ]:
import os

folders = [

    "Salary_Slip",

    "Invoice",

    "Contract",

    "Bank_Statement",

    "Leave_Form",

    "HR_Policy",

    "Meeting_Minutes",

    "NDA",

    "Tax_Report",

    "Firewall_Configuration",

    "Source_Code",

    "Marketing_Brochure"

]

for folder in folders:

    if os.path.exists(folder):

        print(folder, "✓")

    else:

        print(folder, "✗")

Salary_Slip ✓
Invoice ✓
Contract ✓
Bank_Statement ✓
Leave_Form ✓
HR_Policy ✓
Meeting_Minutes ✓
NDA ✓
Tax_Report ✓
Firewall_Configuration ✓
Source_Code ✓
Marketing_Brochure ✓

In [ ]:
import pandas as pd

metadata = []

In [ ]:
def add_metadata(
    filename,
    document_type,
    department,
    classification,
    file_format,
    risk
):

    metadata.append({

        "File Name": filename,

        "Document Type": document_type,

        "Department": department,

        "Classification": classification,

        "File Format": file_format,

        "Risk": risk

    })

In [ ]:
add_metadata(

    "Salary_Slip_001.pdf",

    "Salary Slip",

    "HR",

    "Confidential",

    "PDF",

    "High"

)

metadata

[{'File Name': 'Salary_Slip_001.pdf',
  'Document Type': 'Salary Slip',
  'Department': 'HR',
  'Classification': 'Confidential',
  'File Format': 'PDF',
  'Risk': 'High'}]

In [ ]:
df = pd.DataFrame(metadata)

df.to_csv("dataset_metadata.csv", index=False)

print("Metadata Saved Successfully")

Metadata Saved Successfully

In [ ]:
pd.read_csv("dataset_metadata.csv")

,File Name,Document Type,Department,Classification,File Format,Risk
0,Salary_Slip_001.pdf,Salary Slip,HR,Confidential,PDF,High

In [ ]:
document_generators = {

    "Salary Slip": create_salary_data,

    "Invoice": create_invoice_data,

    "Contract": create_contract_data,

    "Bank Statement": create_bank_statement_data,

    "Leave Form": create_leave_form_data,

    "HR Policy": create_hr_policy_data,

    "Meeting Minutes": create_meeting_minutes_data,

    "NDA": create_nda_data,

    "Tax Report": create_tax_report_data,

    "Firewall Configuration": create_firewall_configuration_data,

    "Source Code": create_source_code_data,

    "Marketing Brochure": create_marketing_brochure_data

}

In [ ]:
template_registry = {

    "Salary Slip":"salary_slip.json",

    "Invoice":"invoice.json",

    "Contract":"contract.json",

    "Bank Statement":"bank_statement.json",

    "Leave Form":"leave_form.json",

    "HR Policy":"hr_policy.json",

    "Meeting Minutes":"meeting_minutes.json",

    "NDA":"nda.json",

    "Tax Report":"tax_report.json",

    "Firewall Configuration":"firewall_configuration.json",

    "Source Code":"source_code.json",

    "Marketing Brochure":"marketing_brochure.json"

}

In [ ]:
classification_registry = {

    "Salary Slip":("HR","Confidential","High"),

    "Invoice":("Finance","Internal","Medium"),

    "Contract":("Legal","Restricted","Critical"),

    "Bank Statement":("Finance","Confidential","High"),

    "Leave Form":("HR","Internal","Low"),

    "HR Policy":("HR","Internal","Low"),

    "Meeting Minutes":("Operations","Internal","Medium"),

    "NDA":("Legal","Restricted","Critical"),

    "Tax Report":("Finance","Confidential","High"),

    "Firewall Configuration":("IT","Restricted","Critical"),

    "Source Code":("IT","Restricted","Critical"),

    "Marketing Brochure":("Marketing","Public","Low")

}

In [ ]:
import pandas as pd

def generate_complete_dataset(documents_per_type=10):

    metadata = []

    for document_type, generator in document_generators.items():

        template = template_registry[document_type]

        department, classification, risk = classification_registry[document_type]

        for i in range(1, documents_per_type + 1):

            data = generator()

            generate_document_from_template(

                template,

                data,

                i

            )

            folder = document_type.replace(" ", "_")

            base = f"{folder}/{folder}_{i:03d}"

            for fmt in ["txt","docx","pdf","png"]:

                metadata.append({

                    "File Name":f"{base}.{fmt}",

                    "Document Type":document_type,

                    "Department":department,

                    "Classification":classification,

                    "Risk":risk,

                    "Format":fmt.upper()

                })

    df = pd.DataFrame(metadata)

    df.to_csv(

        "dataset_metadata.csv",

        index=False

    )

    print("=================================")

    print("Dataset Generation Completed")

    print("Metadata Saved")

    print("=================================")

    return df

In [ ]:
generate_complete_dataset(
    documents_per_type=2
)

Salary_Slip/Salary_Slip_001.txt Created
Salary_Slip/Salary_Slip_001.docx Created
Salary_Slip/Salary_Slip_001.pdf Created
Salary_Slip/Salary_Slip_001.png Created
Salary Slip Generated Successfully
Salary_Slip/Salary_Slip_002.txt Created
Salary_Slip/Salary_Slip_002.docx Created
Salary_Slip/Salary_Slip_002.pdf Created
Salary_Slip/Salary_Slip_002.png Created
Salary Slip Generated Successfully
Invoice/Invoice_001.txt Created
Invoice/Invoice_001.docx Created
Invoice/Invoice_001.pdf Created
Invoice/Invoice_001.png Created
Invoice Generated Successfully
Invoice/Invoice_002.txt Created
Invoice/Invoice_002.docx Created
Invoice/Invoice_002.pdf Created
Invoice/Invoice_002.png Created
Invoice Generated Successfully
Contract/Contract_001.txt Created
Contract/Contract_001.docx Created
Contract/Contract_001.pdf Created
Contract/Contract_001.png Created
Contract Generated Successfully
Contract/Contract_002.txt Created
Contract/Contract_002.docx Created
Contract/Contract_002.pdf Created
Contract/Contract_002.png Created
Contract Generated Successfully
Bank_Statement/Bank_Statement_001.txt Created
Bank_Statement/Bank_Statement_001.docx Created
Bank_Statement/Bank_Statement_001.pdf Created
Bank_Statement/Bank_Statement_001.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_002.txt Created
Bank_Statement/Bank_Statement_002.docx Created
Bank_Statement/Bank_Statement_002.pdf Created
Bank_Statement/Bank_Statement_002.png Created
Bank Statement Generated Successfully
Leave_Form/Leave_Form_001.txt Created
Leave_Form/Leave_Form_001.docx Created
Leave_Form/Leave_Form_001.pdf Created
Leave_Form/Leave_Form_001.png Created
Leave Form Generated Successfully
Leave_Form/Leave_Form_002.txt Created
Leave_Form/Leave_Form_002.docx Created
Leave_Form/Leave_Form_002.pdf Created
Leave_Form/Leave_Form_002.png Created
Leave Form Generated Successfully
HR_Policy/HR_Policy_001.txt Created
HR_Policy/HR_Policy_001.docx Created
HR_Policy/HR_Policy_001.pdf Created
HR_Policy/HR_Policy_001.png Created
HR Policy Generated Successfully
HR_Policy/HR_Policy_002.txt Created
HR_Policy/HR_Policy_002.docx Created
HR_Policy/HR_Policy_002.pdf Created
HR_Policy/HR_Policy_002.png Created
HR Policy Generated Successfully
Meeting_Minutes/Meeting_Minutes_001.txt Created
Meeting_Minutes/Meeting_Minutes_001.docx Created
Meeting_Minutes/Meeting_Minutes_001.pdf Created
Meeting_Minutes/Meeting_Minutes_001.png Created
Meeting Minutes Generated Successfully
Meeting_Minutes/Meeting_Minutes_002.txt Created
Meeting_Minutes/Meeting_Minutes_002.docx Created
Meeting_Minutes/Meeting_Minutes_002.pdf Created
Meeting_Minutes/Meeting_Minutes_002.png Created
Meeting Minutes Generated Successfully
NDA/NDA_001.txt Created
NDA/NDA_001.docx Created
NDA/NDA_001.pdf Created
NDA/NDA_001.png Created
NDA Generated Successfully
NDA/NDA_002.txt Created
NDA/NDA_002.docx Created
NDA/NDA_002.pdf Created
NDA/NDA_002.png Created
NDA Generated Successfully
Tax_Report/Tax_Report_001.txt Created
Tax_Report/Tax_Report_001.docx Created
Tax_Report/Tax_Report_001.pdf Created
Tax_Report/Tax_Report_001.png Created
Tax Report Generated Successfully
Tax_Report/Tax_Report_002.txt Created
Tax_Report/Tax_Report_002.docx Created
Tax_Report/Tax_Report_002.pdf Created
Tax_Report/Tax_Report_002.png Created
Tax Report Generated Successfully
Firewall_Configuration/Firewall_Configuration_001.txt Created
Firewall_Configuration/Firewall_Configuration_001.docx Created
Firewall_Configuration/Firewall_Configuration_001.pdf Created
Firewall_Configuration/Firewall_Configuration_001.png Created
Firewall Configuration Generated Successfully
Firewall_Configuration/Firewall_Configuration_002.txt Created
Firewall_Configuration/Firewall_Configuration_002.docx Created
Firewall_Configuration/Firewall_Configuration_002.pdf Created
Firewall_Configuration/Firewall_Configuration_002.png Created
Firewall Configuration Generated Successfully
Source_Code/Source_Code_001.txt Created
Source_Code/Source_Code_001.docx Created
Source_Code/Source_Code_001.pdf Created
Source_Code/Source_Code_001.png Created
Source Code Generated Successfully
Source_Code/Source_Code_002.txt Created
Source_Code/Source_Code_002.docx Created
Source_Code/Source_Code_002.pdf Created
Source_Code/Source_Code_002.png Created
Source Code Generated Successfully
Marketing_Brochure/Marketing_Brochure_001.txt Created
Marketing_Brochure/Marketing_Brochure_001.docx Created
Marketing_Brochure/Marketing_Brochure_001.pdf Created
Marketing_Brochure/Marketing_Brochure_001.png Created
Marketing Brochure Generated Successfully
Marketing_Brochure/Marketing_Brochure_002.txt Created
Marketing_Brochure/Marketing_Brochure_002.docx Created
Marketing_Brochure/Marketing_Brochure_002.pdf Created
Marketing_Brochure/Marketing_Brochure_002.png Created
Marketing Brochure Generated Successfully
=================================
Dataset Generation Completed
Metadata Saved
=================================

,File Name,Document Type,Department,Classification,Risk,Format
0,Salary_Slip/Salary_Slip_001.txt,Salary Slip,HR,Confidential,High,TXT
1,Salary_Slip/Salary_Slip_001.docx,Salary Slip,HR,Confidential,High,DOCX
2,Salary_Slip/Salary_Slip_001.pdf,Salary Slip,HR,Confidential,High,PDF
3,Salary_Slip/Salary_Slip_001.png,Salary Slip,HR,Confidential,High,PNG
4,Salary_Slip/Salary_Slip_002.txt,Salary Slip,HR,Confidential,High,TXT
...,...,...,...,...,...,...
91,Marketing_Brochure/Marketing_Brochure_001.png,Marketing Brochure,Marketing,Public,Low,PNG
92,Marketing_Brochure/Marketing_Brochure_002.txt,Marketing Brochure,Marketing,Public,Low,TXT
93,Marketing_Brochure/Marketing_Brochure_002.docx,Marketing Brochure,Marketing,Public,Low,DOCX
94,Marketing_Brochure/Marketing_Brochure_002.pdf,Marketing Brochure,Marketing,Public,Low,PDF
95,Marketing_Brochure/Marketing_Brochure_002.png,Marketing Brochure,Marketing,Public,Low,PNG

In [ ]:
df = pd.read_csv("dataset_metadata.csv")

df.head()

,File Name,Document Type,Department,Classification,Risk,Format
0,Salary_Slip/Salary_Slip_001.txt,Salary Slip,HR,Confidential,High,TXT
1,Salary_Slip/Salary_Slip_001.docx,Salary Slip,HR,Confidential,High,DOCX
2,Salary_Slip/Salary_Slip_001.pdf,Salary Slip,HR,Confidential,High,PDF
3,Salary_Slip/Salary_Slip_001.png,Salary Slip,HR,Confidential,High,PNG
4,Salary_Slip/Salary_Slip_002.txt,Salary Slip,HR,Confidential,High,TXT

In [ ]:
print(df.shape)

(96, 6)

In [ ]:
generate_complete_dataset(
    documents_per_type=100
)

Streaming output truncated to the last 5000 lines.
Contract Generated Successfully
Contract/Contract_002.txt Created
Contract/Contract_002.docx Created
Contract/Contract_002.pdf Created
Contract/Contract_002.png Created
Contract Generated Successfully
Contract/Contract_003.txt Created
Contract/Contract_003.docx Created
Contract/Contract_003.pdf Created
Contract/Contract_003.png Created
Contract Generated Successfully
Contract/Contract_004.txt Created
Contract/Contract_004.docx Created
Contract/Contract_004.pdf Created
Contract/Contract_004.png Created
Contract Generated Successfully
Contract/Contract_005.txt Created
Contract/Contract_005.docx Created
Contract/Contract_005.pdf Created
Contract/Contract_005.png Created
Contract Generated Successfully
Contract/Contract_006.txt Created
Contract/Contract_006.docx Created
Contract/Contract_006.pdf Created
Contract/Contract_006.png Created
Contract Generated Successfully
Contract/Contract_007.txt Created
Contract/Contract_007.docx Created
Contract/Contract_007.pdf Created
Contract/Contract_007.png Created
Contract Generated Successfully
Contract/Contract_008.txt Created
Contract/Contract_008.docx Created
Contract/Contract_008.pdf Created
Contract/Contract_008.png Created
Contract Generated Successfully
Contract/Contract_009.txt Created
Contract/Contract_009.docx Created
Contract/Contract_009.pdf Created
Contract/Contract_009.png Created
Contract Generated Successfully
Contract/Contract_010.txt Created
Contract/Contract_010.docx Created
Contract/Contract_010.pdf Created
Contract/Contract_010.png Created
Contract Generated Successfully
Contract/Contract_011.txt Created
Contract/Contract_011.docx Created
Contract/Contract_011.pdf Created
Contract/Contract_011.png Created
Contract Generated Successfully
Contract/Contract_012.txt Created
Contract/Contract_012.docx Created
Contract/Contract_012.pdf Created
Contract/Contract_012.png Created
Contract Generated Successfully
Contract/Contract_013.txt Created
Contract/Contract_013.docx Created
Contract/Contract_013.pdf Created
Contract/Contract_013.png Created
Contract Generated Successfully
Contract/Contract_014.txt Created
Contract/Contract_014.docx Created
Contract/Contract_014.pdf Created
Contract/Contract_014.png Created
Contract Generated Successfully
Contract/Contract_015.txt Created
Contract/Contract_015.docx Created
Contract/Contract_015.pdf Created
Contract/Contract_015.png Created
Contract Generated Successfully
Contract/Contract_016.txt Created
Contract/Contract_016.docx Created
Contract/Contract_016.pdf Created
Contract/Contract_016.png Created
Contract Generated Successfully
Contract/Contract_017.txt Created
Contract/Contract_017.docx Created
Contract/Contract_017.pdf Created
Contract/Contract_017.png Created
Contract Generated Successfully
Contract/Contract_018.txt Created
Contract/Contract_018.docx Created
Contract/Contract_018.pdf Created
Contract/Contract_018.png Created
Contract Generated Successfully
Contract/Contract_019.txt Created
Contract/Contract_019.docx Created
Contract/Contract_019.pdf Created
Contract/Contract_019.png Created
Contract Generated Successfully
Contract/Contract_020.txt Created
Contract/Contract_020.docx Created
Contract/Contract_020.pdf Created
Contract/Contract_020.png Created
Contract Generated Successfully
Contract/Contract_021.txt Created
Contract/Contract_021.docx Created
Contract/Contract_021.pdf Created
Contract/Contract_021.png Created
Contract Generated Successfully
Contract/Contract_022.txt Created
Contract/Contract_022.docx Created
Contract/Contract_022.pdf Created
Contract/Contract_022.png Created
Contract Generated Successfully
Contract/Contract_023.txt Created
Contract/Contract_023.docx Created
Contract/Contract_023.pdf Created
Contract/Contract_023.png Created
Contract Generated Successfully
Contract/Contract_024.txt Created
Contract/Contract_024.docx Created
Contract/Contract_024.pdf Created
Contract/Contract_024.png Created
Contract Generated Successfully
Contract/Contract_025.txt Created
Contract/Contract_025.docx Created
Contract/Contract_025.pdf Created
Contract/Contract_025.png Created
Contract Generated Successfully
Contract/Contract_026.txt Created
Contract/Contract_026.docx Created
Contract/Contract_026.pdf Created
Contract/Contract_026.png Created
Contract Generated Successfully
Contract/Contract_027.txt Created
Contract/Contract_027.docx Created
Contract/Contract_027.pdf Created
Contract/Contract_027.png Created
Contract Generated Successfully
Contract/Contract_028.txt Created
Contract/Contract_028.docx Created
Contract/Contract_028.pdf Created
Contract/Contract_028.png Created
Contract Generated Successfully
Contract/Contract_029.txt Created
Contract/Contract_029.docx Created
Contract/Contract_029.pdf Created
Contract/Contract_029.png Created
Contract Generated Successfully
Contract/Contract_030.txt Created
Contract/Contract_030.docx Created
Contract/Contract_030.pdf Created
Contract/Contract_030.png Created
Contract Generated Successfully
Contract/Contract_031.txt Created
Contract/Contract_031.docx Created
Contract/Contract_031.pdf Created
Contract/Contract_031.png Created
Contract Generated Successfully
Contract/Contract_032.txt Created
Contract/Contract_032.docx Created
Contract/Contract_032.pdf Created
Contract/Contract_032.png Created
Contract Generated Successfully
Contract/Contract_033.txt Created
Contract/Contract_033.docx Created
Contract/Contract_033.pdf Created
Contract/Contract_033.png Created
Contract Generated Successfully
Contract/Contract_034.txt Created
Contract/Contract_034.docx Created
Contract/Contract_034.pdf Created
Contract/Contract_034.png Created
Contract Generated Successfully
Contract/Contract_035.txt Created
Contract/Contract_035.docx Created
Contract/Contract_035.pdf Created
Contract/Contract_035.png Created
Contract Generated Successfully
Contract/Contract_036.txt Created
Contract/Contract_036.docx Created
Contract/Contract_036.pdf Created
Contract/Contract_036.png Created
Contract Generated Successfully
Contract/Contract_037.txt Created
Contract/Contract_037.docx Created
Contract/Contract_037.pdf Created
Contract/Contract_037.png Created
Contract Generated Successfully
Contract/Contract_038.txt Created
Contract/Contract_038.docx Created
Contract/Contract_038.pdf Created
Contract/Contract_038.png Created
Contract Generated Successfully
Contract/Contract_039.txt Created
Contract/Contract_039.docx Created
Contract/Contract_039.pdf Created
Contract/Contract_039.png Created
Contract Generated Successfully
Contract/Contract_040.txt Created
Contract/Contract_040.docx Created
Contract/Contract_040.pdf Created
Contract/Contract_040.png Created
Contract Generated Successfully
Contract/Contract_041.txt Created
Contract/Contract_041.docx Created
Contract/Contract_041.pdf Created
Contract/Contract_041.png Created
Contract Generated Successfully
Contract/Contract_042.txt Created
Contract/Contract_042.docx Created
Contract/Contract_042.pdf Created
Contract/Contract_042.png Created
Contract Generated Successfully
Contract/Contract_043.txt Created
Contract/Contract_043.docx Created
Contract/Contract_043.pdf Created
Contract/Contract_043.png Created
Contract Generated Successfully
Contract/Contract_044.txt Created
Contract/Contract_044.docx Created
Contract/Contract_044.pdf Created
Contract/Contract_044.png Created
Contract Generated Successfully
Contract/Contract_045.txt Created
Contract/Contract_045.docx Created
Contract/Contract_045.pdf Created
Contract/Contract_045.png Created
Contract Generated Successfully
Contract/Contract_046.txt Created
Contract/Contract_046.docx Created
Contract/Contract_046.pdf Created
Contract/Contract_046.png Created
Contract Generated Successfully
Contract/Contract_047.txt Created
Contract/Contract_047.docx Created
Contract/Contract_047.pdf Created
Contract/Contract_047.png Created
Contract Generated Successfully
Contract/Contract_048.txt Created
Contract/Contract_048.docx Created
Contract/Contract_048.pdf Created
Contract/Contract_048.png Created
Contract Generated Successfully
Contract/Contract_049.txt Created
Contract/Contract_049.docx Created
Contract/Contract_049.pdf Created
Contract/Contract_049.png Created
Contract Generated Successfully
Contract/Contract_050.txt Created
Contract/Contract_050.docx Created
Contract/Contract_050.pdf Created
Contract/Contract_050.png Created
Contract Generated Successfully
Contract/Contract_051.txt Created
Contract/Contract_051.docx Created
Contract/Contract_051.pdf Created
Contract/Contract_051.png Created
Contract Generated Successfully
Contract/Contract_052.txt Created
Contract/Contract_052.docx Created
Contract/Contract_052.pdf Created
Contract/Contract_052.png Created
Contract Generated Successfully
Contract/Contract_053.txt Created
Contract/Contract_053.docx Created
Contract/Contract_053.pdf Created
Contract/Contract_053.png Created
Contract Generated Successfully
Contract/Contract_054.txt Created
Contract/Contract_054.docx Created
Contract/Contract_054.pdf Created
Contract/Contract_054.png Created
Contract Generated Successfully
Contract/Contract_055.txt Created
Contract/Contract_055.docx Created
Contract/Contract_055.pdf Created
Contract/Contract_055.png Created
Contract Generated Successfully
Contract/Contract_056.txt Created
Contract/Contract_056.docx Created
Contract/Contract_056.pdf Created
Contract/Contract_056.png Created
Contract Generated Successfully
Contract/Contract_057.txt Created
Contract/Contract_057.docx Created
Contract/Contract_057.pdf Created
Contract/Contract_057.png Created
Contract Generated Successfully
Contract/Contract_058.txt Created
Contract/Contract_058.docx Created
Contract/Contract_058.pdf Created
Contract/Contract_058.png Created
Contract Generated Successfully
Contract/Contract_059.txt Created
Contract/Contract_059.docx Created
Contract/Contract_059.pdf Created
Contract/Contract_059.png Created
Contract Generated Successfully
Contract/Contract_060.txt Created
Contract/Contract_060.docx Created
Contract/Contract_060.pdf Created
Contract/Contract_060.png Created
Contract Generated Successfully
Contract/Contract_061.txt Created
Contract/Contract_061.docx Created
Contract/Contract_061.pdf Created
Contract/Contract_061.png Created
Contract Generated Successfully
Contract/Contract_062.txt Created
Contract/Contract_062.docx Created
Contract/Contract_062.pdf Created
Contract/Contract_062.png Created
Contract Generated Successfully
Contract/Contract_063.txt Created
Contract/Contract_063.docx Created
Contract/Contract_063.pdf Created
Contract/Contract_063.png Created
Contract Generated Successfully
Contract/Contract_064.txt Created
Contract/Contract_064.docx Created
Contract/Contract_064.pdf Created
Contract/Contract_064.png Created
Contract Generated Successfully
Contract/Contract_065.txt Created
Contract/Contract_065.docx Created
Contract/Contract_065.pdf Created
Contract/Contract_065.png Created
Contract Generated Successfully
Contract/Contract_066.txt Created
Contract/Contract_066.docx Created
Contract/Contract_066.pdf Created
Contract/Contract_066.png Created
Contract Generated Successfully
Contract/Contract_067.txt Created
Contract/Contract_067.docx Created
Contract/Contract_067.pdf Created
Contract/Contract_067.png Created
Contract Generated Successfully
Contract/Contract_068.txt Created
Contract/Contract_068.docx Created
Contract/Contract_068.pdf Created
Contract/Contract_068.png Created
Contract Generated Successfully
Contract/Contract_069.txt Created
Contract/Contract_069.docx Created
Contract/Contract_069.pdf Created
Contract/Contract_069.png Created
Contract Generated Successfully
Contract/Contract_070.txt Created
Contract/Contract_070.docx Created
Contract/Contract_070.pdf Created
Contract/Contract_070.png Created
Contract Generated Successfully
Contract/Contract_071.txt Created
Contract/Contract_071.docx Created
Contract/Contract_071.pdf Created
Contract/Contract_071.png Created
Contract Generated Successfully
Contract/Contract_072.txt Created
Contract/Contract_072.docx Created
Contract/Contract_072.pdf Created
Contract/Contract_072.png Created
Contract Generated Successfully
Contract/Contract_073.txt Created
Contract/Contract_073.docx Created
Contract/Contract_073.pdf Created
Contract/Contract_073.png Created
Contract Generated Successfully
Contract/Contract_074.txt Created
Contract/Contract_074.docx Created
Contract/Contract_074.pdf Created
Contract/Contract_074.png Created
Contract Generated Successfully
Contract/Contract_075.txt Created
Contract/Contract_075.docx Created
Contract/Contract_075.pdf Created
Contract/Contract_075.png Created
Contract Generated Successfully
Contract/Contract_076.txt Created
Contract/Contract_076.docx Created
Contract/Contract_076.pdf Created
Contract/Contract_076.png Created
Contract Generated Successfully
Contract/Contract_077.txt Created
Contract/Contract_077.docx Created
Contract/Contract_077.pdf Created
Contract/Contract_077.png Created
Contract Generated Successfully
Contract/Contract_078.txt Created
Contract/Contract_078.docx Created
Contract/Contract_078.pdf Created
Contract/Contract_078.png Created
Contract Generated Successfully
Contract/Contract_079.txt Created
Contract/Contract_079.docx Created
Contract/Contract_079.pdf Created
Contract/Contract_079.png Created
Contract Generated Successfully
Contract/Contract_080.txt Created
Contract/Contract_080.docx Created
Contract/Contract_080.pdf Created
Contract/Contract_080.png Created
Contract Generated Successfully
Contract/Contract_081.txt Created
Contract/Contract_081.docx Created
Contract/Contract_081.pdf Created
Contract/Contract_081.png Created
Contract Generated Successfully
Contract/Contract_082.txt Created
Contract/Contract_082.docx Created
Contract/Contract_082.pdf Created
Contract/Contract_082.png Created
Contract Generated Successfully
Contract/Contract_083.txt Created
Contract/Contract_083.docx Created
Contract/Contract_083.pdf Created
Contract/Contract_083.png Created
Contract Generated Successfully
Contract/Contract_084.txt Created
Contract/Contract_084.docx Created
Contract/Contract_084.pdf Created
Contract/Contract_084.png Created
Contract Generated Successfully
Contract/Contract_085.txt Created
Contract/Contract_085.docx Created
Contract/Contract_085.pdf Created
Contract/Contract_085.png Created
Contract Generated Successfully
Contract/Contract_086.txt Created
Contract/Contract_086.docx Created
Contract/Contract_086.pdf Created
Contract/Contract_086.png Created
Contract Generated Successfully
Contract/Contract_087.txt Created
Contract/Contract_087.docx Created
Contract/Contract_087.pdf Created
Contract/Contract_087.png Created
Contract Generated Successfully
Contract/Contract_088.txt Created
Contract/Contract_088.docx Created
Contract/Contract_088.pdf Created
Contract/Contract_088.png Created
Contract Generated Successfully
Contract/Contract_089.txt Created
Contract/Contract_089.docx Created
Contract/Contract_089.pdf Created
Contract/Contract_089.png Created
Contract Generated Successfully
Contract/Contract_090.txt Created
Contract/Contract_090.docx Created
Contract/Contract_090.pdf Created
Contract/Contract_090.png Created
Contract Generated Successfully
Contract/Contract_091.txt Created
Contract/Contract_091.docx Created
Contract/Contract_091.pdf Created
Contract/Contract_091.png Created
Contract Generated Successfully
Contract/Contract_092.txt Created
Contract/Contract_092.docx Created
Contract/Contract_092.pdf Created
Contract/Contract_092.png Created
Contract Generated Successfully
Contract/Contract_093.txt Created
Contract/Contract_093.docx Created
Contract/Contract_093.pdf Created
Contract/Contract_093.png Created
Contract Generated Successfully
Contract/Contract_094.txt Created
Contract/Contract_094.docx Created
Contract/Contract_094.pdf Created
Contract/Contract_094.png Created
Contract Generated Successfully
Contract/Contract_095.txt Created
Contract/Contract_095.docx Created
Contract/Contract_095.pdf Created
Contract/Contract_095.png Created
Contract Generated Successfully
Contract/Contract_096.txt Created
Contract/Contract_096.docx Created
Contract/Contract_096.pdf Created
Contract/Contract_096.png Created
Contract Generated Successfully
Contract/Contract_097.txt Created
Contract/Contract_097.docx Created
Contract/Contract_097.pdf Created
Contract/Contract_097.png Created
Contract Generated Successfully
Contract/Contract_098.txt Created
Contract/Contract_098.docx Created
Contract/Contract_098.pdf Created
Contract/Contract_098.png Created
Contract Generated Successfully
Contract/Contract_099.txt Created
Contract/Contract_099.docx Created
Contract/Contract_099.pdf Created
Contract/Contract_099.png Created
Contract Generated Successfully
Contract/Contract_100.txt Created
Contract/Contract_100.docx Created
Contract/Contract_100.pdf Created
Contract/Contract_100.png Created
Contract Generated Successfully
Bank_Statement/Bank_Statement_001.txt Created
Bank_Statement/Bank_Statement_001.docx Created
Bank_Statement/Bank_Statement_001.pdf Created
Bank_Statement/Bank_Statement_001.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_002.txt Created
Bank_Statement/Bank_Statement_002.docx Created
Bank_Statement/Bank_Statement_002.pdf Created
Bank_Statement/Bank_Statement_002.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_003.txt Created
Bank_Statement/Bank_Statement_003.docx Created
Bank_Statement/Bank_Statement_003.pdf Created
Bank_Statement/Bank_Statement_003.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_004.txt Created
Bank_Statement/Bank_Statement_004.docx Created
Bank_Statement/Bank_Statement_004.pdf Created
Bank_Statement/Bank_Statement_004.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_005.txt Created
Bank_Statement/Bank_Statement_005.docx Created
Bank_Statement/Bank_Statement_005.pdf Created
Bank_Statement/Bank_Statement_005.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_006.txt Created
Bank_Statement/Bank_Statement_006.docx Created
Bank_Statement/Bank_Statement_006.pdf Created
Bank_Statement/Bank_Statement_006.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_007.txt Created
Bank_Statement/Bank_Statement_007.docx Created
Bank_Statement/Bank_Statement_007.pdf Created
Bank_Statement/Bank_Statement_007.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_008.txt Created
Bank_Statement/Bank_Statement_008.docx Created
Bank_Statement/Bank_Statement_008.pdf Created
Bank_Statement/Bank_Statement_008.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_009.txt Created
Bank_Statement/Bank_Statement_009.docx Created
Bank_Statement/Bank_Statement_009.pdf Created
Bank_Statement/Bank_Statement_009.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_010.txt Created
Bank_Statement/Bank_Statement_010.docx Created
Bank_Statement/Bank_Statement_010.pdf Created
Bank_Statement/Bank_Statement_010.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_011.txt Created
Bank_Statement/Bank_Statement_011.docx Created
Bank_Statement/Bank_Statement_011.pdf Created
Bank_Statement/Bank_Statement_011.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_012.txt Created
Bank_Statement/Bank_Statement_012.docx Created
Bank_Statement/Bank_Statement_012.pdf Created
Bank_Statement/Bank_Statement_012.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_013.txt Created
Bank_Statement/Bank_Statement_013.docx Created
Bank_Statement/Bank_Statement_013.pdf Created
Bank_Statement/Bank_Statement_013.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_014.txt Created
Bank_Statement/Bank_Statement_014.docx Created
Bank_Statement/Bank_Statement_014.pdf Created
Bank_Statement/Bank_Statement_014.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_015.txt Created

,File Name,Document Type,Department,Classification,Risk,Format
0,Salary_Slip/Salary_Slip_001.txt,Salary Slip,HR,Confidential,High,TXT
1,Salary_Slip/Salary_Slip_001.docx,Salary Slip,HR,Confidential,High,DOCX
2,Salary_Slip/Salary_Slip_001.pdf,Salary Slip,HR,Confidential,High,PDF
3,Salary_Slip/Salary_Slip_001.png,Salary Slip,HR,Confidential,High,PNG
4,Salary_Slip/Salary_Slip_002.txt,Salary Slip,HR,Confidential,High,TXT
...,...,...,...,...,...,...
4795,Marketing_Brochure/Marketing_Brochure_099.png,Marketing Brochure,Marketing,Public,Low,PNG
4796,Marketing_Brochure/Marketing_Brochure_100.txt,Marketing Brochure,Marketing,Public,Low,TXT
4797,Marketing_Brochure/Marketing_Brochure_100.docx,Marketing Brochure,Marketing,Public,Low,DOCX
4798,Marketing_Brochure/Marketing_Brochure_100.pdf,Marketing Brochure,Marketing,Public,Low,PDF
4799,Marketing_Brochure/Marketing_Brochure_100.png,Marketing Brochure,Marketing,Public,Low,PNG

In [ ]:
df = generate_complete_dataset(
    documents_per_type=5
)

Salary_Slip/Salary_Slip_001.txt Created
Salary_Slip/Salary_Slip_001.docx Created
Salary_Slip/Salary_Slip_001.pdf Created
Salary_Slip/Salary_Slip_001.png Created
Salary Slip Generated Successfully
Salary_Slip/Salary_Slip_002.txt Created
Salary_Slip/Salary_Slip_002.docx Created
Salary_Slip/Salary_Slip_002.pdf Created
Salary_Slip/Salary_Slip_002.png Created
Salary Slip Generated Successfully
Salary_Slip/Salary_Slip_003.txt Created
Salary_Slip/Salary_Slip_003.docx Created
Salary_Slip/Salary_Slip_003.pdf Created
Salary_Slip/Salary_Slip_003.png Created
Salary Slip Generated Successfully
Salary_Slip/Salary_Slip_004.txt Created
Salary_Slip/Salary_Slip_004.docx Created
Salary_Slip/Salary_Slip_004.pdf Created
Salary_Slip/Salary_Slip_004.png Created
Salary Slip Generated Successfully
Salary_Slip/Salary_Slip_005.txt Created
Salary_Slip/Salary_Slip_005.docx Created
Salary_Slip/Salary_Slip_005.pdf Created
Salary_Slip/Salary_Slip_005.png Created
Salary Slip Generated Successfully
Invoice/Invoice_001.txt Created
Invoice/Invoice_001.docx Created
Invoice/Invoice_001.pdf Created
Invoice/Invoice_001.png Created
Invoice Generated Successfully
Invoice/Invoice_002.txt Created
Invoice/Invoice_002.docx Created
Invoice/Invoice_002.pdf Created
Invoice/Invoice_002.png Created
Invoice Generated Successfully
Invoice/Invoice_003.txt Created
Invoice/Invoice_003.docx Created
Invoice/Invoice_003.pdf Created
Invoice/Invoice_003.png Created
Invoice Generated Successfully
Invoice/Invoice_004.txt Created
Invoice/Invoice_004.docx Created
Invoice/Invoice_004.pdf Created
Invoice/Invoice_004.png Created
Invoice Generated Successfully
Invoice/Invoice_005.txt Created
Invoice/Invoice_005.docx Created
Invoice/Invoice_005.pdf Created
Invoice/Invoice_005.png Created
Invoice Generated Successfully
Contract/Contract_001.txt Created
Contract/Contract_001.docx Created
Contract/Contract_001.pdf Created
Contract/Contract_001.png Created
Contract Generated Successfully
Contract/Contract_002.txt Created
Contract/Contract_002.docx Created
Contract/Contract_002.pdf Created
Contract/Contract_002.png Created
Contract Generated Successfully
Contract/Contract_003.txt Created
Contract/Contract_003.docx Created
Contract/Contract_003.pdf Created
Contract/Contract_003.png Created
Contract Generated Successfully
Contract/Contract_004.txt Created
Contract/Contract_004.docx Created
Contract/Contract_004.pdf Created
Contract/Contract_004.png Created
Contract Generated Successfully
Contract/Contract_005.txt Created
Contract/Contract_005.docx Created
Contract/Contract_005.pdf Created
Contract/Contract_005.png Created
Contract Generated Successfully
Bank_Statement/Bank_Statement_001.txt Created
Bank_Statement/Bank_Statement_001.docx Created
Bank_Statement/Bank_Statement_001.pdf Created
Bank_Statement/Bank_Statement_001.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_002.txt Created
Bank_Statement/Bank_Statement_002.docx Created
Bank_Statement/Bank_Statement_002.pdf Created
Bank_Statement/Bank_Statement_002.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_003.txt Created
Bank_Statement/Bank_Statement_003.docx Created
Bank_Statement/Bank_Statement_003.pdf Created
Bank_Statement/Bank_Statement_003.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_004.txt Created
Bank_Statement/Bank_Statement_004.docx Created
Bank_Statement/Bank_Statement_004.pdf Created
Bank_Statement/Bank_Statement_004.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_005.txt Created
Bank_Statement/Bank_Statement_005.docx Created
Bank_Statement/Bank_Statement_005.pdf Created
Bank_Statement/Bank_Statement_005.png Created
Bank Statement Generated Successfully
Leave_Form/Leave_Form_001.txt Created
Leave_Form/Leave_Form_001.docx Created
Leave_Form/Leave_Form_001.pdf Created
Leave_Form/Leave_Form_001.png Created
Leave Form Generated Successfully
Leave_Form/Leave_Form_002.txt Created
Leave_Form/Leave_Form_002.docx Created
Leave_Form/Leave_Form_002.pdf Created
Leave_Form/Leave_Form_002.png Created
Leave Form Generated Successfully
Leave_Form/Leave_Form_003.txt Created
Leave_Form/Leave_Form_003.docx Created
Leave_Form/Leave_Form_003.pdf Created
Leave_Form/Leave_Form_003.png Created
Leave Form Generated Successfully
Leave_Form/Leave_Form_004.txt Created
Leave_Form/Leave_Form_004.docx Created
Leave_Form/Leave_Form_004.pdf Created
Leave_Form/Leave_Form_004.png Created
Leave Form Generated Successfully
Leave_Form/Leave_Form_005.txt Created
Leave_Form/Leave_Form_005.docx Created
Leave_Form/Leave_Form_005.pdf Created
Leave_Form/Leave_Form_005.png Created
Leave Form Generated Successfully
HR_Policy/HR_Policy_001.txt Created
HR_Policy/HR_Policy_001.docx Created
HR_Policy/HR_Policy_001.pdf Created
HR_Policy/HR_Policy_001.png Created
HR Policy Generated Successfully
HR_Policy/HR_Policy_002.txt Created
HR_Policy/HR_Policy_002.docx Created
HR_Policy/HR_Policy_002.pdf Created
HR_Policy/HR_Policy_002.png Created
HR Policy Generated Successfully
HR_Policy/HR_Policy_003.txt Created
HR_Policy/HR_Policy_003.docx Created
HR_Policy/HR_Policy_003.pdf Created
HR_Policy/HR_Policy_003.png Created
HR Policy Generated Successfully
HR_Policy/HR_Policy_004.txt Created
HR_Policy/HR_Policy_004.docx Created
HR_Policy/HR_Policy_004.pdf Created
HR_Policy/HR_Policy_004.png Created
HR Policy Generated Successfully
HR_Policy/HR_Policy_005.txt Created
HR_Policy/HR_Policy_005.docx Created
HR_Policy/HR_Policy_005.pdf Created
HR_Policy/HR_Policy_005.png Created
HR Policy Generated Successfully
Meeting_Minutes/Meeting_Minutes_001.txt Created
Meeting_Minutes/Meeting_Minutes_001.docx Created
Meeting_Minutes/Meeting_Minutes_001.pdf Created
Meeting_Minutes/Meeting_Minutes_001.png Created
Meeting Minutes Generated Successfully
Meeting_Minutes/Meeting_Minutes_002.txt Created
Meeting_Minutes/Meeting_Minutes_002.docx Created
Meeting_Minutes/Meeting_Minutes_002.pdf Created
Meeting_Minutes/Meeting_Minutes_002.png Created
Meeting Minutes Generated Successfully
Meeting_Minutes/Meeting_Minutes_003.txt Created
Meeting_Minutes/Meeting_Minutes_003.docx Created
Meeting_Minutes/Meeting_Minutes_003.pdf Created
Meeting_Minutes/Meeting_Minutes_003.png Created
Meeting Minutes Generated Successfully
Meeting_Minutes/Meeting_Minutes_004.txt Created
Meeting_Minutes/Meeting_Minutes_004.docx Created
Meeting_Minutes/Meeting_Minutes_004.pdf Created
Meeting_Minutes/Meeting_Minutes_004.png Created
Meeting Minutes Generated Successfully
Meeting_Minutes/Meeting_Minutes_005.txt Created
Meeting_Minutes/Meeting_Minutes_005.docx Created
Meeting_Minutes/Meeting_Minutes_005.pdf Created
Meeting_Minutes/Meeting_Minutes_005.png Created
Meeting Minutes Generated Successfully
NDA/NDA_001.txt Created
NDA/NDA_001.docx Created
NDA/NDA_001.pdf Created
NDA/NDA_001.png Created
NDA Generated Successfully
NDA/NDA_002.txt Created
NDA/NDA_002.docx Created
NDA/NDA_002.pdf Created
NDA/NDA_002.png Created
NDA Generated Successfully
NDA/NDA_003.txt Created
NDA/NDA_003.docx Created
NDA/NDA_003.pdf Created
NDA/NDA_003.png Created
NDA Generated Successfully
NDA/NDA_004.txt Created
NDA/NDA_004.docx Created
NDA/NDA_004.pdf Created
NDA/NDA_004.png Created
NDA Generated Successfully
NDA/NDA_005.txt Created
NDA/NDA_005.docx Created
NDA/NDA_005.pdf Created
NDA/NDA_005.png Created
NDA Generated Successfully
Tax_Report/Tax_Report_001.txt Created
Tax_Report/Tax_Report_001.docx Created
Tax_Report/Tax_Report_001.pdf Created
Tax_Report/Tax_Report_001.png Created
Tax Report Generated Successfully
Tax_Report/Tax_Report_002.txt Created
Tax_Report/Tax_Report_002.docx Created
Tax_Report/Tax_Report_002.pdf Created
Tax_Report/Tax_Report_002.png Created
Tax Report Generated Successfully
Tax_Report/Tax_Report_003.txt Created
Tax_Report/Tax_Report_003.docx Created
Tax_Report/Tax_Report_003.pdf Created
Tax_Report/Tax_Report_003.png Created
Tax Report Generated Successfully
Tax_Report/Tax_Report_004.txt Created
Tax_Report/Tax_Report_004.docx Created
Tax_Report/Tax_Report_004.pdf Created
Tax_Report/Tax_Report_004.png Created
Tax Report Generated Successfully
Tax_Report/Tax_Report_005.txt Created
Tax_Report/Tax_Report_005.docx Created
Tax_Report/Tax_Report_005.pdf Created
Tax_Report/Tax_Report_005.png Created
Tax Report Generated Successfully
Firewall_Configuration/Firewall_Configuration_001.txt Created
Firewall_Configuration/Firewall_Configuration_001.docx Created
Firewall_Configuration/Firewall_Configuration_001.pdf Created
Firewall_Configuration/Firewall_Configuration_001.png Created
Firewall Configuration Generated Successfully
Firewall_Configuration/Firewall_Configuration_002.txt Created
Firewall_Configuration/Firewall_Configuration_002.docx Created
Firewall_Configuration/Firewall_Configuration_002.pdf Created
Firewall_Configuration/Firewall_Configuration_002.png Created
Firewall Configuration Generated Successfully
Firewall_Configuration/Firewall_Configuration_003.txt Created
Firewall_Configuration/Firewall_Configuration_003.docx Created
Firewall_Configuration/Firewall_Configuration_003.pdf Created
Firewall_Configuration/Firewall_Configuration_003.png Created
Firewall Configuration Generated Successfully
Firewall_Configuration/Firewall_Configuration_004.txt Created
Firewall_Configuration/Firewall_Configuration_004.docx Created
Firewall_Configuration/Firewall_Configuration_004.pdf Created
Firewall_Configuration/Firewall_Configuration_004.png Created
Firewall Configuration Generated Successfully
Firewall_Configuration/Firewall_Configuration_005.txt Created
Firewall_Configuration/Firewall_Configuration_005.docx Created
Firewall_Configuration/Firewall_Configuration_005.pdf Created
Firewall_Configuration/Firewall_Configuration_005.png Created
Firewall Configuration Generated Successfully
Source_Code/Source_Code_001.txt Created
Source_Code/Source_Code_001.docx Created
Source_Code/Source_Code_001.pdf Created
Source_Code/Source_Code_001.png Created
Source Code Generated Successfully
Source_Code/Source_Code_002.txt Created
Source_Code/Source_Code_002.docx Created
Source_Code/Source_Code_002.pdf Created
Source_Code/Source_Code_002.png Created
Source Code Generated Successfully
Source_Code/Source_Code_003.txt Created
Source_Code/Source_Code_003.docx Created
Source_Code/Source_Code_003.pdf Created
Source_Code/Source_Code_003.png Created
Source Code Generated Successfully
Source_Code/Source_Code_004.txt Created
Source_Code/Source_Code_004.docx Created
Source_Code/Source_Code_004.pdf Created
Source_Code/Source_Code_004.png Created
Source Code Generated Successfully
Source_Code/Source_Code_005.txt Created
Source_Code/Source_Code_005.docx Created
Source_Code/Source_Code_005.pdf Created
Source_Code/Source_Code_005.png Created
Source Code Generated Successfully
Marketing_Brochure/Marketing_Brochure_001.txt Created
Marketing_Brochure/Marketing_Brochure_001.docx Created
Marketing_Brochure/Marketing_Brochure_001.pdf Created
Marketing_Brochure/Marketing_Brochure_001.png Created
Marketing Brochure Generated Successfully
Marketing_Brochure/Marketing_Brochure_002.txt Created
Marketing_Brochure/Marketing_Brochure_002.docx Created
Marketing_Brochure/Marketing_Brochure_002.pdf Created
Marketing_Brochure/Marketing_Brochure_002.png Created
Marketing Brochure Generated Successfully
Marketing_Brochure/Marketing_Brochure_003.txt Created
Marketing_Brochure/Marketing_Brochure_003.docx Created
Marketing_Brochure/Marketing_Brochure_003.pdf Created
Marketing_Brochure/Marketing_Brochure_003.png Created
Marketing Brochure Generated Successfully
Marketing_Brochure/Marketing_Brochure_004.txt Created
Marketing_Brochure/Marketing_Brochure_004.docx Created
Marketing_Brochure/Marketing_Brochure_004.pdf Created
Marketing_Brochure/Marketing_Brochure_004.png Created
Marketing Brochure Generated Successfully
Marketing_Brochure/Marketing_Brochure_005.txt Created
Marketing_Brochure/Marketing_Brochure_005.docx Created
Marketing_Brochure/Marketing_Brochure_005.pdf Created
Marketing_Brochure/Marketing_Brochure_005.png Created
Marketing Brochure Generated Successfully
=================================
Dataset Generation Completed
Metadata Saved
=================================

In [ ]:
print(df.shape)

(240, 6)

In [ ]:
df.head(10)

,File Name,Document Type,Department,Classification,Risk,Format
0,Salary_Slip/Salary_Slip_001.txt,Salary Slip,HR,Confidential,High,TXT
1,Salary_Slip/Salary_Slip_001.docx,Salary Slip,HR,Confidential,High,DOCX
2,Salary_Slip/Salary_Slip_001.pdf,Salary Slip,HR,Confidential,High,PDF
3,Salary_Slip/Salary_Slip_001.png,Salary Slip,HR,Confidential,High,PNG
4,Salary_Slip/Salary_Slip_002.txt,Salary Slip,HR,Confidential,High,TXT
5,Salary_Slip/Salary_Slip_002.docx,Salary Slip,HR,Confidential,High,DOCX
6,Salary_Slip/Salary_Slip_002.pdf,Salary Slip,HR,Confidential,High,PDF
7,Salary_Slip/Salary_Slip_002.png,Salary Slip,HR,Confidential,High,PNG
8,Salary_Slip/Salary_Slip_003.txt,Salary Slip,HR,Confidential,High,TXT
9,Salary_Slip/Salary_Slip_003.docx,Salary Slip,HR,Confidential,High,DOCX

In [ ]:
import os

for folder in os.listdir():

    if os.path.isdir(folder):

        print(folder)

.config
Invoice
Contract
Salary_Slip
Source_Code
Bank_Statement
Leave_Form
Meeting_Minutes
Firewall_Configuration
Tax_Report
NDA
Marketing_Brochure
templates
HR_Policy
sample_data

In [ ]:
df = generate_complete_dataset(
    documents_per_type=100
)

Streaming output truncated to the last 5000 lines.
Contract Generated Successfully
Contract/Contract_002.txt Created
Contract/Contract_002.docx Created
Contract/Contract_002.pdf Created
Contract/Contract_002.png Created
Contract Generated Successfully
Contract/Contract_003.txt Created
Contract/Contract_003.docx Created
Contract/Contract_003.pdf Created
Contract/Contract_003.png Created
Contract Generated Successfully
Contract/Contract_004.txt Created
Contract/Contract_004.docx Created
Contract/Contract_004.pdf Created
Contract/Contract_004.png Created
Contract Generated Successfully
Contract/Contract_005.txt Created
Contract/Contract_005.docx Created
Contract/Contract_005.pdf Created
Contract/Contract_005.png Created
Contract Generated Successfully
Contract/Contract_006.txt Created
Contract/Contract_006.docx Created
Contract/Contract_006.pdf Created
Contract/Contract_006.png Created
Contract Generated Successfully
Contract/Contract_007.txt Created
Contract/Contract_007.docx Created
Contract/Contract_007.pdf Created
Contract/Contract_007.png Created
Contract Generated Successfully
Contract/Contract_008.txt Created
Contract/Contract_008.docx Created
Contract/Contract_008.pdf Created
Contract/Contract_008.png Created
Contract Generated Successfully
Contract/Contract_009.txt Created
Contract/Contract_009.docx Created
Contract/Contract_009.pdf Created
Contract/Contract_009.png Created
Contract Generated Successfully
Contract/Contract_010.txt Created
Contract/Contract_010.docx Created
Contract/Contract_010.pdf Created
Contract/Contract_010.png Created
Contract Generated Successfully
Contract/Contract_011.txt Created
Contract/Contract_011.docx Created
Contract/Contract_011.pdf Created
Contract/Contract_011.png Created
Contract Generated Successfully
Contract/Contract_012.txt Created
Contract/Contract_012.docx Created
Contract/Contract_012.pdf Created
Contract/Contract_012.png Created
Contract Generated Successfully
Contract/Contract_013.txt Created
Contract/Contract_013.docx Created
Contract/Contract_013.pdf Created
Contract/Contract_013.png Created
Contract Generated Successfully
Contract/Contract_014.txt Created
Contract/Contract_014.docx Created
Contract/Contract_014.pdf Created
Contract/Contract_014.png Created
Contract Generated Successfully
Contract/Contract_015.txt Created
Contract/Contract_015.docx Created
Contract/Contract_015.pdf Created
Contract/Contract_015.png Created
Contract Generated Successfully
Contract/Contract_016.txt Created
Contract/Contract_016.docx Created
Contract/Contract_016.pdf Created
Contract/Contract_016.png Created
Contract Generated Successfully
Contract/Contract_017.txt Created
Contract/Contract_017.docx Created
Contract/Contract_017.pdf Created
Contract/Contract_017.png Created
Contract Generated Successfully
Contract/Contract_018.txt Created
Contract/Contract_018.docx Created
Contract/Contract_018.pdf Created
Contract/Contract_018.png Created
Contract Generated Successfully
Contract/Contract_019.txt Created
Contract/Contract_019.docx Created
Contract/Contract_019.pdf Created
Contract/Contract_019.png Created
Contract Generated Successfully
Contract/Contract_020.txt Created
Contract/Contract_020.docx Created
Contract/Contract_020.pdf Created
Contract/Contract_020.png Created
Contract Generated Successfully
Contract/Contract_021.txt Created
Contract/Contract_021.docx Created
Contract/Contract_021.pdf Created
Contract/Contract_021.png Created
Contract Generated Successfully
Contract/Contract_022.txt Created
Contract/Contract_022.docx Created
Contract/Contract_022.pdf Created
Contract/Contract_022.png Created
Contract Generated Successfully
Contract/Contract_023.txt Created
Contract/Contract_023.docx Created
Contract/Contract_023.pdf Created
Contract/Contract_023.png Created
Contract Generated Successfully
Contract/Contract_024.txt Created
Contract/Contract_024.docx Created
Contract/Contract_024.pdf Created
Contract/Contract_024.png Created
Contract Generated Successfully
Contract/Contract_025.txt Created
Contract/Contract_025.docx Created
Contract/Contract_025.pdf Created
Contract/Contract_025.png Created
Contract Generated Successfully
Contract/Contract_026.txt Created
Contract/Contract_026.docx Created
Contract/Contract_026.pdf Created
Contract/Contract_026.png Created
Contract Generated Successfully
Contract/Contract_027.txt Created
Contract/Contract_027.docx Created
Contract/Contract_027.pdf Created
Contract/Contract_027.png Created
Contract Generated Successfully
Contract/Contract_028.txt Created
Contract/Contract_028.docx Created
Contract/Contract_028.pdf Created
Contract/Contract_028.png Created
Contract Generated Successfully
Contract/Contract_029.txt Created
Contract/Contract_029.docx Created
Contract/Contract_029.pdf Created
Contract/Contract_029.png Created
Contract Generated Successfully
Contract/Contract_030.txt Created
Contract/Contract_030.docx Created
Contract/Contract_030.pdf Created
Contract/Contract_030.png Created
Contract Generated Successfully
Contract/Contract_031.txt Created
Contract/Contract_031.docx Created
Contract/Contract_031.pdf Created
Contract/Contract_031.png Created
Contract Generated Successfully
Contract/Contract_032.txt Created
Contract/Contract_032.docx Created
Contract/Contract_032.pdf Created
Contract/Contract_032.png Created
Contract Generated Successfully
Contract/Contract_033.txt Created
Contract/Contract_033.docx Created
Contract/Contract_033.pdf Created
Contract/Contract_033.png Created
Contract Generated Successfully
Contract/Contract_034.txt Created
Contract/Contract_034.docx Created
Contract/Contract_034.pdf Created
Contract/Contract_034.png Created
Contract Generated Successfully
Contract/Contract_035.txt Created
Contract/Contract_035.docx Created
Contract/Contract_035.pdf Created
Contract/Contract_035.png Created
Contract Generated Successfully
Contract/Contract_036.txt Created
Contract/Contract_036.docx Created
Contract/Contract_036.pdf Created
Contract/Contract_036.png Created
Contract Generated Successfully
Contract/Contract_037.txt Created
Contract/Contract_037.docx Created
Contract/Contract_037.pdf Created
Contract/Contract_037.png Created
Contract Generated Successfully
Contract/Contract_038.txt Created
Contract/Contract_038.docx Created
Contract/Contract_038.pdf Created
Contract/Contract_038.png Created
Contract Generated Successfully
Contract/Contract_039.txt Created
Contract/Contract_039.docx Created
Contract/Contract_039.pdf Created
Contract/Contract_039.png Created
Contract Generated Successfully
Contract/Contract_040.txt Created
Contract/Contract_040.docx Created
Contract/Contract_040.pdf Created
Contract/Contract_040.png Created
Contract Generated Successfully
Contract/Contract_041.txt Created
Contract/Contract_041.docx Created
Contract/Contract_041.pdf Created
Contract/Contract_041.png Created
Contract Generated Successfully
Contract/Contract_042.txt Created
Contract/Contract_042.docx Created
Contract/Contract_042.pdf Created
Contract/Contract_042.png Created
Contract Generated Successfully
Contract/Contract_043.txt Created
Contract/Contract_043.docx Created
Contract/Contract_043.pdf Created
Contract/Contract_043.png Created
Contract Generated Successfully
Contract/Contract_044.txt Created
Contract/Contract_044.docx Created
Contract/Contract_044.pdf Created
Contract/Contract_044.png Created
Contract Generated Successfully
Contract/Contract_045.txt Created
Contract/Contract_045.docx Created
Contract/Contract_045.pdf Created
Contract/Contract_045.png Created
Contract Generated Successfully
Contract/Contract_046.txt Created
Contract/Contract_046.docx Created
Contract/Contract_046.pdf Created
Contract/Contract_046.png Created
Contract Generated Successfully
Contract/Contract_047.txt Created
Contract/Contract_047.docx Created
Contract/Contract_047.pdf Created
Contract/Contract_047.png Created
Contract Generated Successfully
Contract/Contract_048.txt Created
Contract/Contract_048.docx Created
Contract/Contract_048.pdf Created
Contract/Contract_048.png Created
Contract Generated Successfully
Contract/Contract_049.txt Created
Contract/Contract_049.docx Created
Contract/Contract_049.pdf Created
Contract/Contract_049.png Created
Contract Generated Successfully
Contract/Contract_050.txt Created
Contract/Contract_050.docx Created
Contract/Contract_050.pdf Created
Contract/Contract_050.png Created
Contract Generated Successfully
Contract/Contract_051.txt Created
Contract/Contract_051.docx Created
Contract/Contract_051.pdf Created
Contract/Contract_051.png Created
Contract Generated Successfully
Contract/Contract_052.txt Created
Contract/Contract_052.docx Created
Contract/Contract_052.pdf Created
Contract/Contract_052.png Created
Contract Generated Successfully
Contract/Contract_053.txt Created
Contract/Contract_053.docx Created
Contract/Contract_053.pdf Created
Contract/Contract_053.png Created
Contract Generated Successfully
Contract/Contract_054.txt Created
Contract/Contract_054.docx Created
Contract/Contract_054.pdf Created
Contract/Contract_054.png Created
Contract Generated Successfully
Contract/Contract_055.txt Created
Contract/Contract_055.docx Created
Contract/Contract_055.pdf Created
Contract/Contract_055.png Created
Contract Generated Successfully
Contract/Contract_056.txt Created
Contract/Contract_056.docx Created
Contract/Contract_056.pdf Created
Contract/Contract_056.png Created
Contract Generated Successfully
Contract/Contract_057.txt Created
Contract/Contract_057.docx Created
Contract/Contract_057.pdf Created
Contract/Contract_057.png Created
Contract Generated Successfully
Contract/Contract_058.txt Created
Contract/Contract_058.docx Created
Contract/Contract_058.pdf Created
Contract/Contract_058.png Created
Contract Generated Successfully
Contract/Contract_059.txt Created
Contract/Contract_059.docx Created
Contract/Contract_059.pdf Created
Contract/Contract_059.png Created
Contract Generated Successfully
Contract/Contract_060.txt Created
Contract/Contract_060.docx Created
Contract/Contract_060.pdf Created
Contract/Contract_060.png Created
Contract Generated Successfully
Contract/Contract_061.txt Created
Contract/Contract_061.docx Created
Contract/Contract_061.pdf Created
Contract/Contract_061.png Created
Contract Generated Successfully
Contract/Contract_062.txt Created
Contract/Contract_062.docx Created
Contract/Contract_062.pdf Created
Contract/Contract_062.png Created
Contract Generated Successfully
Contract/Contract_063.txt Created
Contract/Contract_063.docx Created
Contract/Contract_063.pdf Created
Contract/Contract_063.png Created
Contract Generated Successfully
Contract/Contract_064.txt Created
Contract/Contract_064.docx Created
Contract/Contract_064.pdf Created
Contract/Contract_064.png Created
Contract Generated Successfully
Contract/Contract_065.txt Created
Contract/Contract_065.docx Created
Contract/Contract_065.pdf Created
Contract/Contract_065.png Created
Contract Generated Successfully
Contract/Contract_066.txt Created
Contract/Contract_066.docx Created
Contract/Contract_066.pdf Created
Contract/Contract_066.png Created
Contract Generated Successfully
Contract/Contract_067.txt Created
Contract/Contract_067.docx Created
Contract/Contract_067.pdf Created
Contract/Contract_067.png Created
Contract Generated Successfully
Contract/Contract_068.txt Created
Contract/Contract_068.docx Created
Contract/Contract_068.pdf Created
Contract/Contract_068.png Created
Contract Generated Successfully
Contract/Contract_069.txt Created
Contract/Contract_069.docx Created
Contract/Contract_069.pdf Created
Contract/Contract_069.png Created
Contract Generated Successfully
Contract/Contract_070.txt Created
Contract/Contract_070.docx Created
Contract/Contract_070.pdf Created
Contract/Contract_070.png Created
Contract Generated Successfully
Contract/Contract_071.txt Created
Contract/Contract_071.docx Created
Contract/Contract_071.pdf Created
Contract/Contract_071.png Created
Contract Generated Successfully
Contract/Contract_072.txt Created
Contract/Contract_072.docx Created
Contract/Contract_072.pdf Created
Contract/Contract_072.png Created
Contract Generated Successfully
Contract/Contract_073.txt Created
Contract/Contract_073.docx Created
Contract/Contract_073.pdf Created
Contract/Contract_073.png Created
Contract Generated Successfully
Contract/Contract_074.txt Created
Contract/Contract_074.docx Created
Contract/Contract_074.pdf Created
Contract/Contract_074.png Created
Contract Generated Successfully
Contract/Contract_075.txt Created
Contract/Contract_075.docx Created
Contract/Contract_075.pdf Created
Contract/Contract_075.png Created
Contract Generated Successfully
Contract/Contract_076.txt Created
Contract/Contract_076.docx Created
Contract/Contract_076.pdf Created
Contract/Contract_076.png Created
Contract Generated Successfully
Contract/Contract_077.txt Created
Contract/Contract_077.docx Created
Contract/Contract_077.pdf Created
Contract/Contract_077.png Created
Contract Generated Successfully
Contract/Contract_078.txt Created
Contract/Contract_078.docx Created
Contract/Contract_078.pdf Created
Contract/Contract_078.png Created
Contract Generated Successfully
Contract/Contract_079.txt Created
Contract/Contract_079.docx Created
Contract/Contract_079.pdf Created
Contract/Contract_079.png Created
Contract Generated Successfully
Contract/Contract_080.txt Created
Contract/Contract_080.docx Created
Contract/Contract_080.pdf Created
Contract/Contract_080.png Created
Contract Generated Successfully
Contract/Contract_081.txt Created
Contract/Contract_081.docx Created
Contract/Contract_081.pdf Created
Contract/Contract_081.png Created
Contract Generated Successfully
Contract/Contract_082.txt Created
Contract/Contract_082.docx Created
Contract/Contract_082.pdf Created
Contract/Contract_082.png Created
Contract Generated Successfully
Contract/Contract_083.txt Created
Contract/Contract_083.docx Created
Contract/Contract_083.pdf Created
Contract/Contract_083.png Created
Contract Generated Successfully
Contract/Contract_084.txt Created
Contract/Contract_084.docx Created
Contract/Contract_084.pdf Created
Contract/Contract_084.png Created
Contract Generated Successfully
Contract/Contract_085.txt Created
Contract/Contract_085.docx Created
Contract/Contract_085.pdf Created
Contract/Contract_085.png Created
Contract Generated Successfully
Contract/Contract_086.txt Created
Contract/Contract_086.docx Created
Contract/Contract_086.pdf Created
Contract/Contract_086.png Created
Contract Generated Successfully
Contract/Contract_087.txt Created
Contract/Contract_087.docx Created
Contract/Contract_087.pdf Created
Contract/Contract_087.png Created
Contract Generated Successfully
Contract/Contract_088.txt Created
Contract/Contract_088.docx Created
Contract/Contract_088.pdf Created
Contract/Contract_088.png Created
Contract Generated Successfully
Contract/Contract_089.txt Created
Contract/Contract_089.docx Created
Contract/Contract_089.pdf Created
Contract/Contract_089.png Created
Contract Generated Successfully
Contract/Contract_090.txt Created
Contract/Contract_090.docx Created
Contract/Contract_090.pdf Created
Contract/Contract_090.png Created
Contract Generated Successfully
Contract/Contract_091.txt Created
Contract/Contract_091.docx Created
Contract/Contract_091.pdf Created
Contract/Contract_091.png Created
Contract Generated Successfully
Contract/Contract_092.txt Created
Contract/Contract_092.docx Created
Contract/Contract_092.pdf Created
Contract/Contract_092.png Created
Contract Generated Successfully
Contract/Contract_093.txt Created
Contract/Contract_093.docx Created
Contract/Contract_093.pdf Created
Contract/Contract_093.png Created
Contract Generated Successfully
Contract/Contract_094.txt Created
Contract/Contract_094.docx Created
Contract/Contract_094.pdf Created
Contract/Contract_094.png Created
Contract Generated Successfully
Contract/Contract_095.txt Created
Contract/Contract_095.docx Created
Contract/Contract_095.pdf Created
Contract/Contract_095.png Created
Contract Generated Successfully
Contract/Contract_096.txt Created
Contract/Contract_096.docx Created
Contract/Contract_096.pdf Created
Contract/Contract_096.png Created
Contract Generated Successfully
Contract/Contract_097.txt Created
Contract/Contract_097.docx Created
Contract/Contract_097.pdf Created
Contract/Contract_097.png Created
Contract Generated Successfully
Contract/Contract_098.txt Created
Contract/Contract_098.docx Created
Contract/Contract_098.pdf Created
Contract/Contract_098.png Created
Contract Generated Successfully
Contract/Contract_099.txt Created
Contract/Contract_099.docx Created
Contract/Contract_099.pdf Created
Contract/Contract_099.png Created
Contract Generated Successfully
Contract/Contract_100.txt Created
Contract/Contract_100.docx Created
Contract/Contract_100.pdf Created
Contract/Contract_100.png Created
Contract Generated Successfully
Bank_Statement/Bank_Statement_001.txt Created
Bank_Statement/Bank_Statement_001.docx Created
Bank_Statement/Bank_Statement_001.pdf Created
Bank_Statement/Bank_Statement_001.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_002.txt Created
Bank_Statement/Bank_Statement_002.docx Created
Bank_Statement/Bank_Statement_002.pdf Created
Bank_Statement/Bank_Statement_002.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_003.txt Created
Bank_Statement/Bank_Statement_003.docx Created
Bank_Statement/Bank_Statement_003.pdf Created
Bank_Statement/Bank_Statement_003.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_004.txt Created
Bank_Statement/Bank_Statement_004.docx Created
Bank_Statement/Bank_Statement_004.pdf Created
Bank_Statement/Bank_Statement_004.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_005.txt Created
Bank_Statement/Bank_Statement_005.docx Created
Bank_Statement/Bank_Statement_005.pdf Created
Bank_Statement/Bank_Statement_005.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_006.txt Created
Bank_Statement/Bank_Statement_006.docx Created
Bank_Statement/Bank_Statement_006.pdf Created
Bank_Statement/Bank_Statement_006.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_007.txt Created
Bank_Statement/Bank_Statement_007.docx Created
Bank_Statement/Bank_Statement_007.pdf Created
Bank_Statement/Bank_Statement_007.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_008.txt Created
Bank_Statement/Bank_Statement_008.docx Created
Bank_Statement/Bank_Statement_008.pdf Created
Bank_Statement/Bank_Statement_008.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_009.txt Created
Bank_Statement/Bank_Statement_009.docx Created
Bank_Statement/Bank_Statement_009.pdf Created
Bank_Statement/Bank_Statement_009.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_010.txt Created
Bank_Statement/Bank_Statement_010.docx Created
Bank_Statement/Bank_Statement_010.pdf Created
Bank_Statement/Bank_Statement_010.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_011.txt Created
Bank_Statement/Bank_Statement_011.docx Created
Bank_Statement/Bank_Statement_011.pdf Created
Bank_Statement/Bank_Statement_011.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_012.txt Created
Bank_Statement/Bank_Statement_012.docx Created
Bank_Statement/Bank_Statement_012.pdf Created
Bank_Statement/Bank_Statement_012.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_013.txt Created
Bank_Statement/Bank_Statement_013.docx Created
Bank_Statement/Bank_Statement_013.pdf Created
Bank_Statement/Bank_Statement_013.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_014.txt Created
Bank_Statement/Bank_Statement_014.docx Created
Bank_Statement/Bank_Statement_014.pdf Created
Bank_Statement/Bank_Statement_014.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_015.txt Created

In [ ]:
import pandas as pd

df = pd.read_csv("dataset_metadata.csv")

print(df.shape)

df.head()

(4800, 6)

,File Name,Document Type,Department,Classification,Risk,Format
0,Salary_Slip/Salary_Slip_001.txt,Salary Slip,HR,Confidential,High,TXT
1,Salary_Slip/Salary_Slip_001.docx,Salary Slip,HR,Confidential,High,DOCX
2,Salary_Slip/Salary_Slip_001.pdf,Salary Slip,HR,Confidential,High,PDF
3,Salary_Slip/Salary_Slip_001.png,Salary Slip,HR,Confidential,High,PNG
4,Salary_Slip/Salary_Slip_002.txt,Salary Slip,HR,Confidential,High,TXT

In [ ]:
generate_complete_dataset(
    documents_per_type=100
)

Streaming output truncated to the last 5000 lines.
Contract Generated Successfully
Contract/Contract_002.txt Created
Contract/Contract_002.docx Created
Contract/Contract_002.pdf Created
Contract/Contract_002.png Created
Contract Generated Successfully
Contract/Contract_003.txt Created
Contract/Contract_003.docx Created
Contract/Contract_003.pdf Created
Contract/Contract_003.png Created
Contract Generated Successfully
Contract/Contract_004.txt Created
Contract/Contract_004.docx Created
Contract/Contract_004.pdf Created
Contract/Contract_004.png Created
Contract Generated Successfully
Contract/Contract_005.txt Created
Contract/Contract_005.docx Created
Contract/Contract_005.pdf Created
Contract/Contract_005.png Created
Contract Generated Successfully
Contract/Contract_006.txt Created
Contract/Contract_006.docx Created
Contract/Contract_006.pdf Created
Contract/Contract_006.png Created
Contract Generated Successfully
Contract/Contract_007.txt Created
Contract/Contract_007.docx Created
Contract/Contract_007.pdf Created
Contract/Contract_007.png Created
Contract Generated Successfully
Contract/Contract_008.txt Created
Contract/Contract_008.docx Created
Contract/Contract_008.pdf Created
Contract/Contract_008.png Created
Contract Generated Successfully
Contract/Contract_009.txt Created
Contract/Contract_009.docx Created
Contract/Contract_009.pdf Created
Contract/Contract_009.png Created
Contract Generated Successfully
Contract/Contract_010.txt Created
Contract/Contract_010.docx Created
Contract/Contract_010.pdf Created
Contract/Contract_010.png Created
Contract Generated Successfully
Contract/Contract_011.txt Created
Contract/Contract_011.docx Created
Contract/Contract_011.pdf Created
Contract/Contract_011.png Created
Contract Generated Successfully
Contract/Contract_012.txt Created
Contract/Contract_012.docx Created
Contract/Contract_012.pdf Created
Contract/Contract_012.png Created
Contract Generated Successfully
Contract/Contract_013.txt Created
Contract/Contract_013.docx Created
Contract/Contract_013.pdf Created
Contract/Contract_013.png Created
Contract Generated Successfully
Contract/Contract_014.txt Created
Contract/Contract_014.docx Created
Contract/Contract_014.pdf Created
Contract/Contract_014.png Created
Contract Generated Successfully
Contract/Contract_015.txt Created
Contract/Contract_015.docx Created
Contract/Contract_015.pdf Created
Contract/Contract_015.png Created
Contract Generated Successfully
Contract/Contract_016.txt Created
Contract/Contract_016.docx Created
Contract/Contract_016.pdf Created
Contract/Contract_016.png Created
Contract Generated Successfully
Contract/Contract_017.txt Created
Contract/Contract_017.docx Created
Contract/Contract_017.pdf Created
Contract/Contract_017.png Created
Contract Generated Successfully
Contract/Contract_018.txt Created
Contract/Contract_018.docx Created
Contract/Contract_018.pdf Created
Contract/Contract_018.png Created
Contract Generated Successfully
Contract/Contract_019.txt Created
Contract/Contract_019.docx Created
Contract/Contract_019.pdf Created
Contract/Contract_019.png Created
Contract Generated Successfully
Contract/Contract_020.txt Created
Contract/Contract_020.docx Created
Contract/Contract_020.pdf Created
Contract/Contract_020.png Created
Contract Generated Successfully
Contract/Contract_021.txt Created
Contract/Contract_021.docx Created
Contract/Contract_021.pdf Created
Contract/Contract_021.png Created
Contract Generated Successfully
Contract/Contract_022.txt Created
Contract/Contract_022.docx Created
Contract/Contract_022.pdf Created
Contract/Contract_022.png Created
Contract Generated Successfully
Contract/Contract_023.txt Created
Contract/Contract_023.docx Created
Contract/Contract_023.pdf Created
Contract/Contract_023.png Created
Contract Generated Successfully
Contract/Contract_024.txt Created
Contract/Contract_024.docx Created
Contract/Contract_024.pdf Created
Contract/Contract_024.png Created
Contract Generated Successfully
Contract/Contract_025.txt Created
Contract/Contract_025.docx Created
Contract/Contract_025.pdf Created
Contract/Contract_025.png Created
Contract Generated Successfully
Contract/Contract_026.txt Created
Contract/Contract_026.docx Created
Contract/Contract_026.pdf Created
Contract/Contract_026.png Created
Contract Generated Successfully
Contract/Contract_027.txt Created
Contract/Contract_027.docx Created
Contract/Contract_027.pdf Created
Contract/Contract_027.png Created
Contract Generated Successfully
Contract/Contract_028.txt Created
Contract/Contract_028.docx Created
Contract/Contract_028.pdf Created
Contract/Contract_028.png Created
Contract Generated Successfully
Contract/Contract_029.txt Created
Contract/Contract_029.docx Created
Contract/Contract_029.pdf Created
Contract/Contract_029.png Created
Contract Generated Successfully
Contract/Contract_030.txt Created
Contract/Contract_030.docx Created
Contract/Contract_030.pdf Created
Contract/Contract_030.png Created
Contract Generated Successfully
Contract/Contract_031.txt Created
Contract/Contract_031.docx Created
Contract/Contract_031.pdf Created
Contract/Contract_031.png Created
Contract Generated Successfully
Contract/Contract_032.txt Created
Contract/Contract_032.docx Created
Contract/Contract_032.pdf Created
Contract/Contract_032.png Created
Contract Generated Successfully
Contract/Contract_033.txt Created
Contract/Contract_033.docx Created
Contract/Contract_033.pdf Created
Contract/Contract_033.png Created
Contract Generated Successfully
Contract/Contract_034.txt Created
Contract/Contract_034.docx Created
Contract/Contract_034.pdf Created
Contract/Contract_034.png Created
Contract Generated Successfully
Contract/Contract_035.txt Created
Contract/Contract_035.docx Created
Contract/Contract_035.pdf Created
Contract/Contract_035.png Created
Contract Generated Successfully
Contract/Contract_036.txt Created
Contract/Contract_036.docx Created
Contract/Contract_036.pdf Created
Contract/Contract_036.png Created
Contract Generated Successfully
Contract/Contract_037.txt Created
Contract/Contract_037.docx Created
Contract/Contract_037.pdf Created
Contract/Contract_037.png Created
Contract Generated Successfully
Contract/Contract_038.txt Created
Contract/Contract_038.docx Created
Contract/Contract_038.pdf Created
Contract/Contract_038.png Created
Contract Generated Successfully
Contract/Contract_039.txt Created
Contract/Contract_039.docx Created
Contract/Contract_039.pdf Created
Contract/Contract_039.png Created
Contract Generated Successfully
Contract/Contract_040.txt Created
Contract/Contract_040.docx Created
Contract/Contract_040.pdf Created
Contract/Contract_040.png Created
Contract Generated Successfully
Contract/Contract_041.txt Created
Contract/Contract_041.docx Created
Contract/Contract_041.pdf Created
Contract/Contract_041.png Created
Contract Generated Successfully
Contract/Contract_042.txt Created
Contract/Contract_042.docx Created
Contract/Contract_042.pdf Created
Contract/Contract_042.png Created
Contract Generated Successfully
Contract/Contract_043.txt Created
Contract/Contract_043.docx Created
Contract/Contract_043.pdf Created
Contract/Contract_043.png Created
Contract Generated Successfully
Contract/Contract_044.txt Created
Contract/Contract_044.docx Created
Contract/Contract_044.pdf Created
Contract/Contract_044.png Created
Contract Generated Successfully
Contract/Contract_045.txt Created
Contract/Contract_045.docx Created
Contract/Contract_045.pdf Created
Contract/Contract_045.png Created
Contract Generated Successfully
Contract/Contract_046.txt Created
Contract/Contract_046.docx Created
Contract/Contract_046.pdf Created
Contract/Contract_046.png Created
Contract Generated Successfully
Contract/Contract_047.txt Created
Contract/Contract_047.docx Created
Contract/Contract_047.pdf Created
Contract/Contract_047.png Created
Contract Generated Successfully
Contract/Contract_048.txt Created
Contract/Contract_048.docx Created
Contract/Contract_048.pdf Created
Contract/Contract_048.png Created
Contract Generated Successfully
Contract/Contract_049.txt Created
Contract/Contract_049.docx Created
Contract/Contract_049.pdf Created
Contract/Contract_049.png Created
Contract Generated Successfully
Contract/Contract_050.txt Created
Contract/Contract_050.docx Created
Contract/Contract_050.pdf Created
Contract/Contract_050.png Created
Contract Generated Successfully
Contract/Contract_051.txt Created
Contract/Contract_051.docx Created
Contract/Contract_051.pdf Created
Contract/Contract_051.png Created
Contract Generated Successfully
Contract/Contract_052.txt Created
Contract/Contract_052.docx Created
Contract/Contract_052.pdf Created
Contract/Contract_052.png Created
Contract Generated Successfully
Contract/Contract_053.txt Created
Contract/Contract_053.docx Created
Contract/Contract_053.pdf Created
Contract/Contract_053.png Created
Contract Generated Successfully
Contract/Contract_054.txt Created
Contract/Contract_054.docx Created
Contract/Contract_054.pdf Created
Contract/Contract_054.png Created
Contract Generated Successfully
Contract/Contract_055.txt Created
Contract/Contract_055.docx Created
Contract/Contract_055.pdf Created
Contract/Contract_055.png Created
Contract Generated Successfully
Contract/Contract_056.txt Created
Contract/Contract_056.docx Created
Contract/Contract_056.pdf Created
Contract/Contract_056.png Created
Contract Generated Successfully
Contract/Contract_057.txt Created
Contract/Contract_057.docx Created
Contract/Contract_057.pdf Created
Contract/Contract_057.png Created
Contract Generated Successfully
Contract/Contract_058.txt Created
Contract/Contract_058.docx Created
Contract/Contract_058.pdf Created
Contract/Contract_058.png Created
Contract Generated Successfully
Contract/Contract_059.txt Created
Contract/Contract_059.docx Created
Contract/Contract_059.pdf Created
Contract/Contract_059.png Created
Contract Generated Successfully
Contract/Contract_060.txt Created
Contract/Contract_060.docx Created
Contract/Contract_060.pdf Created
Contract/Contract_060.png Created
Contract Generated Successfully
Contract/Contract_061.txt Created
Contract/Contract_061.docx Created
Contract/Contract_061.pdf Created
Contract/Contract_061.png Created
Contract Generated Successfully
Contract/Contract_062.txt Created
Contract/Contract_062.docx Created
Contract/Contract_062.pdf Created
Contract/Contract_062.png Created
Contract Generated Successfully
Contract/Contract_063.txt Created
Contract/Contract_063.docx Created
Contract/Contract_063.pdf Created
Contract/Contract_063.png Created
Contract Generated Successfully
Contract/Contract_064.txt Created
Contract/Contract_064.docx Created
Contract/Contract_064.pdf Created
Contract/Contract_064.png Created
Contract Generated Successfully
Contract/Contract_065.txt Created
Contract/Contract_065.docx Created
Contract/Contract_065.pdf Created
Contract/Contract_065.png Created
Contract Generated Successfully
Contract/Contract_066.txt Created
Contract/Contract_066.docx Created
Contract/Contract_066.pdf Created
Contract/Contract_066.png Created
Contract Generated Successfully
Contract/Contract_067.txt Created
Contract/Contract_067.docx Created
Contract/Contract_067.pdf Created
Contract/Contract_067.png Created
Contract Generated Successfully
Contract/Contract_068.txt Created
Contract/Contract_068.docx Created
Contract/Contract_068.pdf Created
Contract/Contract_068.png Created
Contract Generated Successfully
Contract/Contract_069.txt Created
Contract/Contract_069.docx Created
Contract/Contract_069.pdf Created
Contract/Contract_069.png Created
Contract Generated Successfully
Contract/Contract_070.txt Created
Contract/Contract_070.docx Created
Contract/Contract_070.pdf Created
Contract/Contract_070.png Created
Contract Generated Successfully
Contract/Contract_071.txt Created
Contract/Contract_071.docx Created
Contract/Contract_071.pdf Created
Contract/Contract_071.png Created
Contract Generated Successfully
Contract/Contract_072.txt Created
Contract/Contract_072.docx Created
Contract/Contract_072.pdf Created
Contract/Contract_072.png Created
Contract Generated Successfully
Contract/Contract_073.txt Created
Contract/Contract_073.docx Created
Contract/Contract_073.pdf Created
Contract/Contract_073.png Created
Contract Generated Successfully
Contract/Contract_074.txt Created
Contract/Contract_074.docx Created
Contract/Contract_074.pdf Created
Contract/Contract_074.png Created
Contract Generated Successfully
Contract/Contract_075.txt Created
Contract/Contract_075.docx Created
Contract/Contract_075.pdf Created
Contract/Contract_075.png Created
Contract Generated Successfully
Contract/Contract_076.txt Created
Contract/Contract_076.docx Created
Contract/Contract_076.pdf Created
Contract/Contract_076.png Created
Contract Generated Successfully
Contract/Contract_077.txt Created
Contract/Contract_077.docx Created
Contract/Contract_077.pdf Created
Contract/Contract_077.png Created
Contract Generated Successfully
Contract/Contract_078.txt Created
Contract/Contract_078.docx Created
Contract/Contract_078.pdf Created
Contract/Contract_078.png Created
Contract Generated Successfully
Contract/Contract_079.txt Created
Contract/Contract_079.docx Created
Contract/Contract_079.pdf Created
Contract/Contract_079.png Created
Contract Generated Successfully
Contract/Contract_080.txt Created
Contract/Contract_080.docx Created
Contract/Contract_080.pdf Created
Contract/Contract_080.png Created
Contract Generated Successfully
Contract/Contract_081.txt Created
Contract/Contract_081.docx Created
Contract/Contract_081.pdf Created
Contract/Contract_081.png Created
Contract Generated Successfully
Contract/Contract_082.txt Created
Contract/Contract_082.docx Created
Contract/Contract_082.pdf Created
Contract/Contract_082.png Created
Contract Generated Successfully
Contract/Contract_083.txt Created
Contract/Contract_083.docx Created
Contract/Contract_083.pdf Created
Contract/Contract_083.png Created
Contract Generated Successfully
Contract/Contract_084.txt Created
Contract/Contract_084.docx Created
Contract/Contract_084.pdf Created
Contract/Contract_084.png Created
Contract Generated Successfully
Contract/Contract_085.txt Created
Contract/Contract_085.docx Created
Contract/Contract_085.pdf Created
Contract/Contract_085.png Created
Contract Generated Successfully
Contract/Contract_086.txt Created
Contract/Contract_086.docx Created
Contract/Contract_086.pdf Created
Contract/Contract_086.png Created
Contract Generated Successfully
Contract/Contract_087.txt Created
Contract/Contract_087.docx Created
Contract/Contract_087.pdf Created
Contract/Contract_087.png Created
Contract Generated Successfully
Contract/Contract_088.txt Created
Contract/Contract_088.docx Created
Contract/Contract_088.pdf Created
Contract/Contract_088.png Created
Contract Generated Successfully
Contract/Contract_089.txt Created
Contract/Contract_089.docx Created
Contract/Contract_089.pdf Created
Contract/Contract_089.png Created
Contract Generated Successfully
Contract/Contract_090.txt Created
Contract/Contract_090.docx Created
Contract/Contract_090.pdf Created
Contract/Contract_090.png Created
Contract Generated Successfully
Contract/Contract_091.txt Created
Contract/Contract_091.docx Created
Contract/Contract_091.pdf Created
Contract/Contract_091.png Created
Contract Generated Successfully
Contract/Contract_092.txt Created
Contract/Contract_092.docx Created
Contract/Contract_092.pdf Created
Contract/Contract_092.png Created
Contract Generated Successfully
Contract/Contract_093.txt Created
Contract/Contract_093.docx Created
Contract/Contract_093.pdf Created
Contract/Contract_093.png Created
Contract Generated Successfully
Contract/Contract_094.txt Created
Contract/Contract_094.docx Created
Contract/Contract_094.pdf Created
Contract/Contract_094.png Created
Contract Generated Successfully
Contract/Contract_095.txt Created
Contract/Contract_095.docx Created
Contract/Contract_095.pdf Created
Contract/Contract_095.png Created
Contract Generated Successfully
Contract/Contract_096.txt Created
Contract/Contract_096.docx Created
Contract/Contract_096.pdf Created
Contract/Contract_096.png Created
Contract Generated Successfully
Contract/Contract_097.txt Created
Contract/Contract_097.docx Created
Contract/Contract_097.pdf Created
Contract/Contract_097.png Created
Contract Generated Successfully
Contract/Contract_098.txt Created
Contract/Contract_098.docx Created
Contract/Contract_098.pdf Created
Contract/Contract_098.png Created
Contract Generated Successfully
Contract/Contract_099.txt Created
Contract/Contract_099.docx Created
Contract/Contract_099.pdf Created
Contract/Contract_099.png Created
Contract Generated Successfully
Contract/Contract_100.txt Created
Contract/Contract_100.docx Created
Contract/Contract_100.pdf Created
Contract/Contract_100.png Created
Contract Generated Successfully
Bank_Statement/Bank_Statement_001.txt Created
Bank_Statement/Bank_Statement_001.docx Created
Bank_Statement/Bank_Statement_001.pdf Created
Bank_Statement/Bank_Statement_001.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_002.txt Created
Bank_Statement/Bank_Statement_002.docx Created
Bank_Statement/Bank_Statement_002.pdf Created
Bank_Statement/Bank_Statement_002.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_003.txt Created
Bank_Statement/Bank_Statement_003.docx Created
Bank_Statement/Bank_Statement_003.pdf Created
Bank_Statement/Bank_Statement_003.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_004.txt Created
Bank_Statement/Bank_Statement_004.docx Created
Bank_Statement/Bank_Statement_004.pdf Created
Bank_Statement/Bank_Statement_004.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_005.txt Created
Bank_Statement/Bank_Statement_005.docx Created
Bank_Statement/Bank_Statement_005.pdf Created
Bank_Statement/Bank_Statement_005.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_006.txt Created
Bank_Statement/Bank_Statement_006.docx Created
Bank_Statement/Bank_Statement_006.pdf Created
Bank_Statement/Bank_Statement_006.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_007.txt Created
Bank_Statement/Bank_Statement_007.docx Created
Bank_Statement/Bank_Statement_007.pdf Created
Bank_Statement/Bank_Statement_007.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_008.txt Created
Bank_Statement/Bank_Statement_008.docx Created
Bank_Statement/Bank_Statement_008.pdf Created
Bank_Statement/Bank_Statement_008.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_009.txt Created
Bank_Statement/Bank_Statement_009.docx Created
Bank_Statement/Bank_Statement_009.pdf Created
Bank_Statement/Bank_Statement_009.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_010.txt Created
Bank_Statement/Bank_Statement_010.docx Created
Bank_Statement/Bank_Statement_010.pdf Created
Bank_Statement/Bank_Statement_010.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_011.txt Created
Bank_Statement/Bank_Statement_011.docx Created
Bank_Statement/Bank_Statement_011.pdf Created
Bank_Statement/Bank_Statement_011.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_012.txt Created
Bank_Statement/Bank_Statement_012.docx Created
Bank_Statement/Bank_Statement_012.pdf Created
Bank_Statement/Bank_Statement_012.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_013.txt Created
Bank_Statement/Bank_Statement_013.docx Created
Bank_Statement/Bank_Statement_013.pdf Created
Bank_Statement/Bank_Statement_013.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_014.txt Created
Bank_Statement/Bank_Statement_014.docx Created
Bank_Statement/Bank_Statement_014.pdf Created
Bank_Statement/Bank_Statement_014.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_015.txt Created

,File Name,Document Type,Department,Classification,Risk,Format
0,Salary_Slip/Salary_Slip_001.txt,Salary Slip,HR,Confidential,High,TXT
1,Salary_Slip/Salary_Slip_001.docx,Salary Slip,HR,Confidential,High,DOCX
2,Salary_Slip/Salary_Slip_001.pdf,Salary Slip,HR,Confidential,High,PDF
3,Salary_Slip/Salary_Slip_001.png,Salary Slip,HR,Confidential,High,PNG
4,Salary_Slip/Salary_Slip_002.txt,Salary Slip,HR,Confidential,High,TXT
...,...,...,...,...,...,...
4795,Marketing_Brochure/Marketing_Brochure_099.png,Marketing Brochure,Marketing,Public,Low,PNG
4796,Marketing_Brochure/Marketing_Brochure_100.txt,Marketing Brochure,Marketing,Public,Low,TXT
4797,Marketing_Brochure/Marketing_Brochure_100.docx,Marketing Brochure,Marketing,Public,Low,DOCX
4798,Marketing_Brochure/Marketing_Brochure_100.pdf,Marketing Brochure,Marketing,Public,Low,PDF
4799,Marketing_Brochure/Marketing_Brochure_100.png,Marketing Brochure,Marketing,Public,Low,PNG

In [ ]:
import pandas as pd

df = pd.read_csv("dataset_metadata.csv")

print(df.shape)

df.head(10)

(4800, 6)

,File Name,Document Type,Department,Classification,Risk,Format
0,Salary_Slip/Salary_Slip_001.txt,Salary Slip,HR,Confidential,High,TXT
1,Salary_Slip/Salary_Slip_001.docx,Salary Slip,HR,Confidential,High,DOCX
2,Salary_Slip/Salary_Slip_001.pdf,Salary Slip,HR,Confidential,High,PDF
3,Salary_Slip/Salary_Slip_001.png,Salary Slip,HR,Confidential,High,PNG
4,Salary_Slip/Salary_Slip_002.txt,Salary Slip,HR,Confidential,High,TXT
5,Salary_Slip/Salary_Slip_002.docx,Salary Slip,HR,Confidential,High,DOCX
6,Salary_Slip/Salary_Slip_002.pdf,Salary Slip,HR,Confidential,High,PDF
7,Salary_Slip/Salary_Slip_002.png,Salary Slip,HR,Confidential,High,PNG
8,Salary_Slip/Salary_Slip_003.txt,Salary Slip,HR,Confidential,High,TXT
9,Salary_Slip/Salary_Slip_003.docx,Salary Slip,HR,Confidential,High,DOCX

In [ ]:
df["Department"].value_counts()

Department
HR            1200
Finance       1200
Legal          800
IT             800
Operations     400
Marketing      400
Name: count, dtype: int64

In [ ]:
df["Document Type"].value_counts()

Document Type
Salary Slip               400
Invoice                   400
Contract                  400
Bank Statement            400
Leave Form                400
HR Policy                 400
Meeting Minutes           400
NDA                       400
Tax Report                400
Firewall Configuration    400
Source Code               400
Marketing Brochure        400
Name: count, dtype: int64

In [ ]:
industry_registry = {

    "Salary Slip": "Banking",
    "Invoice": "Retail",
    "Contract": "Legal",
    "Bank Statement": "Banking",
    "Leave Form": "Corporate",
    "HR Policy": "Corporate",
    "Meeting Minutes": "Corporate",
    "NDA": "Legal",
    "Tax Report": "Finance",
    "Firewall Configuration": "IT",
    "Source Code": "IT",
    "Marketing Brochure": "Marketing"

}

print("Industry Registry Created")

Industry Registry Created

In [ ]:
entity_registry = {

    "Salary Slip": [
        "NIC",
        "Salary",
        "Bank Account"
    ],

    "Invoice": [
        "Invoice Number",
        "Amount"
    ],

    "Contract": [
        "Agreement Number",
        "Client"
    ],

    "Bank Statement": [
        "Account Number",
        "Balance"
    ],

    "Leave Form": [
        "Employee ID"
    ],

    "HR Policy": [
        "Policy Number"
    ],

    "Meeting Minutes": [
        "Attendees"
    ],

    "NDA": [
        "Client",
        "Confidential Information"
    ],

    "Tax Report": [
        "TIN",
        "Revenue",
        "Tax Amount"
    ],

    "Firewall Configuration": [
        "IP Address",
        "VPN"
    ],

    "Source Code": [
        "API Key",
        "Database URL"
    ],

    "Marketing Brochure": [
        "Company",
        "Contact"
    ]
}

print("Entity Registry Created")

Entity Registry Created

In [ ]:
def generate_document_id(number):

    return f"DOC{number:06d}"

print(generate_document_id(1))

DOC000001

In [ ]:
import pandas as pd
import random

def generate_complete_dataset(documents_per_type=100):

    metadata = []

    document_counter = 1

    for document_type, generator in document_generators.items():

        template = template_registry[document_type]

        department, classification, risk = classification_registry[document_type]

        industry = industry_registry[document_type]

        entities = entity_registry[document_type]

        print(f"\nGenerating {document_type}...")

        for i in range(1, documents_per_type + 1):

            data = generator()

            generate_document_from_template(

                template,

                data,

                i

            )

            folder = document_type.replace(" ", "_")

            base = f"{folder}/{folder}_{i:03d}"

            for fmt in ["txt", "docx", "pdf", "png"]:

                metadata.append({

                    "Document ID": generate_document_id(document_counter),

                    "File Name": f"{base}.{fmt}",

                    "Document Type": document_type,

                    "Department": department,

                    "Industry": industry,

                    "Classification": classification,

                    "Risk": risk,

                    "Sensitive Entities": ", ".join(entities),

                    "Leakage Score": random.randint(60,100),

                    "Format": fmt.upper()

                })

                document_counter += 1

    df = pd.DataFrame(metadata)

    df.to_csv(

        "dataset_metadata.csv",

        index=False

    )

    print("\n======================================")

    print("✅ Custom Dataset Generated Successfully")

    print(f"📄 Total Metadata Records : {len(df)}")

    print("💾 dataset_metadata.csv Saved")

    print("======================================")

    return df

In [ ]:
df = generate_complete_dataset(
    documents_per_type=2
)

Generating Salary Slip...
Salary_Slip/Salary_Slip_001.txt Created
Salary_Slip/Salary_Slip_001.docx Created
Salary_Slip/Salary_Slip_001.pdf Created
Salary_Slip/Salary_Slip_001.png Created
Salary Slip Generated Successfully
Salary_Slip/Salary_Slip_002.txt Created
Salary_Slip/Salary_Slip_002.docx Created
Salary_Slip/Salary_Slip_002.pdf Created
Salary_Slip/Salary_Slip_002.png Created
Salary Slip Generated Successfully

Generating Invoice...
Invoice/Invoice_001.txt Created
Invoice/Invoice_001.docx Created
Invoice/Invoice_001.pdf Created
Invoice/Invoice_001.png Created
Invoice Generated Successfully
Invoice/Invoice_002.txt Created
Invoice/Invoice_002.docx Created
Invoice/Invoice_002.pdf Created
Invoice/Invoice_002.png Created
Invoice Generated Successfully

Generating Contract...
Contract/Contract_001.txt Created
Contract/Contract_001.docx Created
Contract/Contract_001.pdf Created
Contract/Contract_001.png Created
Contract Generated Successfully
Contract/Contract_002.txt Created
Contract/Contract_002.docx Created
Contract/Contract_002.pdf Created
Contract/Contract_002.png Created
Contract Generated Successfully

Generating Bank Statement...
Bank_Statement/Bank_Statement_001.txt Created
Bank_Statement/Bank_Statement_001.docx Created
Bank_Statement/Bank_Statement_001.pdf Created
Bank_Statement/Bank_Statement_001.png Created
Bank Statement Generated Successfully
Bank_Statement/Bank_Statement_002.txt Created
Bank_Statement/Bank_Statement_002.docx Created
Bank_Statement/Bank_Statement_002.pdf Created
Bank_Statement/Bank_Statement_002.png Created
Bank Statement Generated Successfully

Generating Leave Form...
Leave_Form/Leave_Form_001.txt Created
Leave_Form/Leave_Form_001.docx Created
Leave_Form/Leave_Form_001.pdf Created
Leave_Form/Leave_Form_001.png Created
Leave Form Generated Successfully
Leave_Form/Leave_Form_002.txt Created
Leave_Form/Leave_Form_002.docx Created
Leave_Form/Leave_Form_002.pdf Created
Leave_Form/Leave_Form_002.png Created
Leave Form Generated Successfully

Generating HR Policy...
HR_Policy/HR_Policy_001.txt Created
HR_Policy/HR_Policy_001.docx Created
HR_Policy/HR_Policy_001.pdf Created
HR_Policy/HR_Policy_001.png Created
HR Policy Generated Successfully
HR_Policy/HR_Policy_002.txt Created
HR_Policy/HR_Policy_002.docx Created
HR_Policy/HR_Policy_002.pdf Created
HR_Policy/HR_Policy_002.png Created
HR Policy Generated Successfully

Generating Meeting Minutes...
Meeting_Minutes/Meeting_Minutes_001.txt Created
Meeting_Minutes/Meeting_Minutes_001.docx Created
Meeting_Minutes/Meeting_Minutes_001.pdf Created
Meeting_Minutes/Meeting_Minutes_001.png Created
Meeting Minutes Generated Successfully
Meeting_Minutes/Meeting_Minutes_002.txt Created
Meeting_Minutes/Meeting_Minutes_002.docx Created
Meeting_Minutes/Meeting_Minutes_002.pdf Created
Meeting_Minutes/Meeting_Minutes_002.png Created
Meeting Minutes Generated Successfully

Generating NDA...
NDA/NDA_001.txt Created
NDA/NDA_001.docx Created
NDA/NDA_001.pdf Created
NDA/NDA_001.png Created
NDA Generated Successfully
NDA/NDA_002.txt Created
NDA/NDA_002.docx Created
NDA/NDA_002.pdf Created
NDA/NDA_002.png Created
NDA Generated Successfully

Generating Tax Report...
Tax_Report/Tax_Report_001.txt Created
Tax_Report/Tax_Report_001.docx Created
Tax_Report/Tax_Report_001.pdf Created
Tax_Report/Tax_Report_001.png Created
Tax Report Generated Successfully
Tax_Report/Tax_Report_002.txt Created
Tax_Report/Tax_Report_002.docx Created
Tax_Report/Tax_Report_002.pdf Created
Tax_Report/Tax_Report_002.png Created
Tax Report Generated Successfully

Generating Firewall Configuration...
Firewall_Configuration/Firewall_Configuration_001.txt Created
Firewall_Configuration/Firewall_Configuration_001.docx Created
Firewall_Configuration/Firewall_Configuration_001.pdf Created
Firewall_Configuration/Firewall_Configuration_001.png Created
Firewall Configuration Generated Successfully
Firewall_Configuration/Firewall_Configuration_002.txt Created
Firewall_Configuration/Firewall_Configuration_002.docx Created
Firewall_Configuration/Firewall_Configuration_002.pdf Created
Firewall_Configuration/Firewall_Configuration_002.png Created
Firewall Configuration Generated Successfully

Generating Source Code...
Source_Code/Source_Code_001.txt Created
Source_Code/Source_Code_001.docx Created
Source_Code/Source_Code_001.pdf Created
Source_Code/Source_Code_001.png Created
Source Code Generated Successfully
Source_Code/Source_Code_002.txt Created
Source_Code/Source_Code_002.docx Created
Source_Code/Source_Code_002.pdf Created
Source_Code/Source_Code_002.png Created
Source Code Generated Successfully

Generating Marketing Brochure...
Marketing_Brochure/Marketing_Brochure_001.txt Created
Marketing_Brochure/Marketing_Brochure_001.docx Created
Marketing_Brochure/Marketing_Brochure_001.pdf Created
Marketing_Brochure/Marketing_Brochure_001.png Created
Marketing Brochure Generated Successfully
Marketing_Brochure/Marketing_Brochure_002.txt Created
Marketing_Brochure/Marketing_Brochure_002.docx Created
Marketing_Brochure/Marketing_Brochure_002.pdf Created
Marketing_Brochure/Marketing_Brochure_002.png Created
Marketing Brochure Generated Successfully

======================================
✅ Custom Dataset Generated Successfully
📄 Total Metadata Records : 96
💾 dataset_metadata.csv Saved
======================================

In [ ]:
print(df.shape)

df.head()

(96, 10)

,Document ID,File Name,Document Type,Department,Industry,Classification,Risk,Sensitive Entities,Leakage Score,Format
0,DOC000001,Salary_Slip/Salary_Slip_001.txt,Salary Slip,HR,Banking,Confidential,High,"NIC, Salary, Bank Account",74,TXT
1,DOC000002,Salary_Slip/Salary_Slip_001.docx,Salary Slip,HR,Banking,Confidential,High,"NIC, Salary, Bank Account",67,DOCX
2,DOC000003,Salary_Slip/Salary_Slip_001.pdf,Salary Slip,HR,Banking,Confidential,High,"NIC, Salary, Bank Account",65,PDF
3,DOC000004,Salary_Slip/Salary_Slip_001.png,Salary Slip,HR,Banking,Confidential,High,"NIC, Salary, Bank Account",86,PNG
4,DOC000005,Salary_Slip/Salary_Slip_002.txt,Salary Slip,HR,Banking,Confidential,High,"NIC, Salary, Bank Account",64,TXT

In [ ]:
df.columns

Index(['Document ID', 'File Name', 'Document Type', 'Department', 'Industry',
       'Classification', 'Risk', 'Sensitive Entities', 'Leakage Score',
       'Format'],
      dtype='object')

In [ ]:
import os
import shutil

os.makedirs("custom_dataset", exist_ok=True)

print("custom_dataset folder created.")

custom_dataset folder created.

In [ ]:
folders = [

    "Salary_Slip",
    "Invoice",
    "Contract",
    "Bank_Statement",
    "Leave_Form",
    "HR_Policy",
    "Meeting_Minutes",
    "NDA",
    "Tax_Report",
    "Firewall_Configuration",
    "Source_Code",
    "Marketing_Brochure"

]

for folder in folders:

    if os.path.exists(folder):

        shutil.move(folder, "custom_dataset")

if os.path.exists("dataset_metadata.csv"):

    shutil.move("dataset_metadata.csv", "custom_dataset")

print("Dataset Organized Successfully")

Dataset Organized Successfully

In [ ]:
shutil.make_archive(

    "custom_dataset",

    "zip",

    "custom_dataset"

)

print("ZIP File Created")

ZIP File Created

In [ ]:
from google.colab import files

files.download("custom_dataset.zip")